### ISSUE TITLE
Theme Documentation

### ISSUE THREAD

**Issue by StephenOTT** [wet-boew/wet-boew-drupal#118]
Is there any documentation that can be posted on how the theme the subtheme(s) has been set up and any relevant documentation?

**Comment by LeeHunter** [comment]
I've started a page on the wiki for theming: https://github.com/wet-boew/wet-boew-drupal/wiki/Theming-Guide 

Not much helpful information yet though.

**Comment by StephenOTT** [comment]
I think one of the most important pieces of information for this section will be "what modifications and catch22s have been made to AT to meet the WET requirements?"

There are a lot of little tweaks and adjustments that were made to integrate with the WET base and what those changes are is important to understand.  Especially if a someone plans on modifying the theme or going back to the AT base and using a subtheme off of the base rather than subtheme off of the WET AT theme.

**Comment by d-shields** [comment]
Hey @sylus and others,
I'm having a tough time setting up a subtheme for a fresh install.
I've tried drush adaptivetheme "Theme Name" theme_name and this installs in 
/home/wetkit/wetkit/profiles/wetkit/themes/ 
rather than where I was hoping it would - in
/home/wetkit/wetkit/sites/drupal_wet/themes

That's fine, though - I don't really care what themes directory I'm using, as long as it works - and it is definitely cool to be able to build subthemes with drush!

When I enable that theme and set it as default, I get a very plain looking AdaptiveTheme that doesn't seem to respond to Panels.

Anyone have any idea what I'm missing here?

Thanks!

**Comment by joejoseph00** [comment]
@StephenOtt , @wet-boew 

I've worked on some of this wet-boew drupal documentation and noticed some people are supplementing the ackronym WET for WxT , this is a bit confusing.  Is it WET or is it WxT ?

So in the french side, can I replace WxT with WET-BOEW or BOEW ?  Or is WxT something other than WET-BOEW or WET?

Thanks.

See the wiki documentation 
https://github.com/wet-boew/wet-boew-drupal/wiki/Wxt-jquery-biblioth%C3%A8que-et-l%27interface-de-programmation-d%27applications

**Comment by StephenOTT** [comment]
@pjackson28, thoughts?

**Comment by pjackson28** [comment]
WxT and WET are interchangeable. We started using WxT because WET as a Twitter hashtag produces undesirable results. WxT also made for a more interesting logo. On the French side, only BOEW is used (for the Twitter hashtag as well). When doing bilingual, we use wet-boew.

**Comment by sylus** [comment]
This looks answered and we have a dedicated documentation issue already so closing.
