### ISSUE TITLE
Performance issue with package (webexp-7.x-1.0)

### ISSUE THREAD

**Issue by finweb** [wet-boew/wet-boew-drupal#137]
Hello,

We have downloaded the previous WET Distro package in February and are halfway completed the implementation for our internal website and ran into a critical performance problem. 

We simulated a performance tuning testing on the environment for multiple concurrence hits on the website and noticed a 90% peak in memory usage. We increased RAM/CPU capacity on the server and still the same results.

We did a comparison performance testing between a vanilla Drupal package and the WET Distro package. The different is enormous. The vanilla version take a few second comparing to the later. We are too far in the implementation phase of the project to use the new version of the WET Distro package.

I am looking for a solution to fix the performance issue. 

• Is there any solution available to increase the performance? For example: snippet PHP code or tweet/modification in WET Distro Drupal. 
• To help us troubleshoot, could someone confirm that the Drupal core has been modified? If yes, which core modules are affected.

General Information:

Drupal version 7.12
Install profile WebExp (webexp-7.x-1.0)
WAMP platform: MySQL 5.5.23, PHP 5.3.14, Apache 2.4.2

Any recommendation or feedback is greatly appreciated.

**Comment by sinkinsona** [comment]
If possible you should upgrade to the latest distro  as we have made many performance improvements.  The WET 3.0 framework fixes / improves load time a lot.

 If this is not an option I would start by removing / disabling any modules that you are not using.  Also to help with anonymous request you can enable caching by going to /configuration/performance.  In our architecture we are also using Varnish and Memcache which significantly improves performance.  Adding these components should really speed things up.

**Comment by sylus** [comment]
This was a known issue with the previous version and the main reason behind the complete reimplementation. In fact the new version of the WET distro boosts a significant reduction in footprint and with panels integration is on par with the performance of vanilla Drupal 7 thanks to its aggressive caching layer. Unfortunately there is very little similarity between these WET versions.

You mention that you are too far into your development to switch. Despite the versions being completely different the upgrade would actually be relatively easy to handle assuming you just did work around content types + views. We could just migrate your content into the new system and export your existing configuration using features. It likely would only take a day or two and would keep you in sync with the newer version of WET and vastly improved architecture (we are basing WET on a well established distro on Drupal.org called Panopoly). As it is important to us to help early adopters I would do whatever I could to assist in a potential upgrade.

I can't recommend enough upgrading to the newer version but if that is not possible. Likely the culprit is the sheer number of modules that are installed in Version 1. You could ideally remove more then half the modules that came with that version and that would likely result in performance improvements. Varnish + Memcache would vastly improve the performance but I still definitely think alot of the extra modules should be removed. So you know Drupal Core was never modified even in that early alpha release.

Ideally I'd love to come in for an hour and maybe take a look as I can only speculate over github what is going on. I did work with another client that was using an early alpha version of the distro and I was able to improve their performance by removing some modules and a few other steps. You could take a look for yourself how fast it is www.scc.ca . If you really couldn't upgrade to the newer version of WET, I would likely strip out many components of WET and bring you closer to vanilla drupal. I could also upgrade you to version 3.0 of WET which with its asynchronous loading would speed up the client side.

It is worth mentioning the newer WET distro features the apps model which Shared Services will be hosting which would further assist in keeping you up to date and in sync with government requirements.

**Comment by thriuin** [comment]
Performance can also be significantly affected by the database  and the web server software you are using. MySQL on Windows is generally noticeably slower than MySQL or Percona on Linux. 32-bit Apache on Windows can be slower than IIS 7 or 64 bit Apache on Linux. If you don't want to touch the web application, you can still tune the performance the these.

You could also consider the Boost module for static pages, but this depends on your software configuration.

**Comment by sylus** [comment]
Hey any status update? I'd love to offer any assistance :)

**Comment by finweb** [comment]
Hello Will,

We have try unsuccessfully to update to the new version using Drush. We are new to Drush.
We have other questions where your expertise is needed. 

How soon would you be available to come in and help us?

Thanks,
Dat

-----Original Message-----

**Comment by sylus** [comment]
I am on vacation next week, but could come in anytime this Thursday or Friday. Additionally when I get back I could most definitely find time. It is very important to us to help early adopters.

I know security is a bit more stringent where you guys are at. So let me know when your able to let me swing by and I will adjust my schedule :)

In the mean time we do have some developer documentation that might assist in getting Drush to work. It is specifically tailored to windows environments.

**Comment by finweb** [comment]
Hello Will,

Thank you for your quick response and your help. I would prefer that you could come in this Thursday.
I will check with our Security and get back to you asap. 

Could you confirm that you have Secret clearance? This will speed up the process enormously.

Dat

-----Original Message-----

**Comment by sylus** [comment]
Hey @finweb,

Unfortunately I only have Enhanced Reliability hopefully that won't be a problem. I was in before about a 8 or so months ago without much hassle.

Let me know ^_^

**Comment by sylus** [comment]
Hey @finweb haven't heard back from you guys? Did you resolve the problem?

**Comment by finweb** [comment]
Hello all,

Sorry for the delay response. We are working very hard to meet our deadlines and the released date.
Drupal is a great tool but challenging. I will keep you posted if there is any other news.
Thank you for all your help.

I will closed this ticket.
