### ISSUE TITLE
UX and Design improvements feedback (Overall)

### ISSUE THREAD

**Issue by sylus** [wet-boew/wet-boew-drupal#1499]
Would like to have a discussion on how we can better improve the admin interface for the new branch.

So far I have made the following improvements and would love feedback and additional recommendations.

**Improvements**
- Navbar replaces admin menu by default
- Navbar has language switcher, mobile preview, and common top level tasks
- Navbar icons have been added for every menu route so will display on small res screens
- Panels IPE no longer takes the full bottom
- Panels IPE icons have been refactored to be much more minimal

**Questions**
- Right now the state change on the icons on hover just switch to black is this enough?
- What about the regions? I don't think light grey is enough to give the user proper context

**Comment by sylus** [comment]
![main_landing_screen](https://cloud.githubusercontent.com/assets/984304/3459915/cf960c58-0211-11e4-8181-7becd9f350d9.png)

**Comment by sylus** [comment]
@aastrong I would love your feedback on other possible improvements perhaps more representative colors? For instance if you look at the "top" and "top inner" I don't think the color really helps the user know those are draggable / dynamic regions.

**Comment by aastrong** [comment]
Hey @sylus, 
I'm really glad we are using navbar instead of admin menu, its cleaner, and uses a lot less room vertically, which is generally where I think we get into problems on the admin side of things. 

For the state change on hover for the icons, do you think we could change it to a blue, similar to the blue in the new layout change in https://github.com/wet-boew/wet-boew-drupal/issues/1500

As for the Top & Top inner, while i do like that it is pretty minimal, i think if we used something darker with white text  & icons it would be a bit better, similar to the navbar. Another option would be the blue I was just referring too, how about I take a few screen shots with a few different options and go from there. 

Lets discuss this further.
