### ISSUE TITLE
Pre-built distribution installation - Install profile step execution time

### ISSUE THREAD

**Issue by stevebauman** [wet-boew/wet-boew-drupal#1645]
When I hit the 'Install Profile' step in the pre-built distribution, it's guaranteed to hit a PHP execution timeout unless I set a huge execution time (I'm talking well over 1000+ seconds), or set it to -1 to allow infinite execution time. 

This is through the browser based installation on a local machine running:
- Windows 8.1
- Apache 2.4.10
- MySQL 5.6.20
- PHP 5.6
- Core i7 @3.1 Ghz
- 8GB DDR3

All my other development sites have absolutely no issues in terms of speed.

Is this intended? If so, the distribution is intended for 'novice' users, however I don't think novice users encountering this issue would know that the execution time in the php.ini needs to be set to a much higher value. Some hosting providers don't allow the modification of execution time which would further complicate the problem.  Not to mention if PHP is crashing from timeouts halfway through, this could definitely lead to corrupt installs (which I've experienced directly from this issue).

Has anyone experienced quick installations via browser? If there's anything I can provide to help with this issue such as logs & more details I'd happily provide them.

Thanks!

**Comment by Pacoup** [comment]
Because of the nature of the distributions' build complexity, it is meant to be [installed with Drush](http://wiki.drupalwxt.org/architecture/drush-make/). PHP's CLI SAPI max_execution_time is also hardcoded to 0 in properly configured environments, so you shouldn't run into any timeout issues using Drush. Drush will also be quicker than running the web-based install.

I'm also pretty sure the distribution is not tailored to novice users. Hosting providers which don't allow modification of execution time are most definitely not fast enough to host a complex Drupal website like wetkit provides. This is meant to run on a capable server.

Besides, managing a Drupal install isn't really an activity for novice users who don't yet know what max_execution_time in PHP is. There's some foundations to learn first, although figuring out how to make wetkit run properly is certainly a nice exercise in and of itself, albeit a frustrating one. That is, users should be comfortable with Bash, PHP, Drupal and Composer, among other things, before they start using wetkit.

**Comment by stevebauman** [comment]
I understand, thanks for the reply. I'm definitely a novice when it comes to drupal, so when I was looking for a specific distribution to use, your `readme.md` suggests the 'Pre-built distribution' for novice users ([link](https://github.com/wet-boew/wet-boew-drupal#installation-methods)). The browser installation was painfully long (around 25-30 minutes) which I'm sure you're already aware of, however I think I'd be nice to include at least a small notice or warning for users looking to install the dist via this method.

I'll definitely use drush for the installation instead, I appreciate the recommendation!

**Comment by Pacoup** [comment]
Oh, right, maybe we should change that. @sylus?

Speaking of web-based installation problems, I've personally never even been able to properly install Drupal 7 via the web interface. They've pretty much stopped supporting any issues with that ever since Drupal 8 development accelerated (the Drupal 8 web install, on the other hand, works very well).

**Comment by stevebauman** [comment]
It installed fine for me through the web install, however when I ran updates on all the modules when it was finished through drupal it failed due the issue described [here](https://www.drupal.org/node/2347267). This is using the `7.x-1.8` recommended release. Though I'll install through drush instead and see if this persists.

**Comment by Pacoup** [comment]
Oh, normally, you're supposed to update wetkit using the distribution files; i.e. you should not manage module updates yourself: http://wiki.drupalwxt.org/architecture/release-cycle/

If you need to update Core for security vulnerabilities, in addition to the /sites folder, you need to make sure /profiles is not touched, because this is where wetkit is installed. A similar process could be used for "out of band" security updates to wetkit modules. I'd recommend to update everything manually and maintain patches for these, since you eventually want to go back to versions managed by the distro. Here's a nice article about good patch management strategies: https://www.lullabot.com/blog/article/strategies-patch-management

You can also combine this with Git, which can help track everything, but do note that as far as `7.x-1.8`, you still need to manually remove .gitignore files from wetkit module folders, or they won't be tracked by Git, which can be done, at least in Bash and maybe only Linux (I didn't test this in OS X or Windows), in one fell swoop from your Drupal root without touching your root .gitignore with this command:

``` Bash
find . -name ".gitignore" -path "./*/*" -exec rm -rf {} \;
```

See: https://www.drupal.org/node/2379961 for more about this problem.

**Comment by stevebauman** [comment]
Oh ok, thanks for the heads up! Shows how much I know about drupal and this variant lol. I appreciate the help!

**Comment by Pacoup** [comment]
Just realized this may delete .gitignore files you actually want to keep, like those from the Apache Solr modules, so you may want to do something like that:

``` Bash
find . -name ".gitignore" -path "./profiles/*" -exec rm -rf {} \;
```

And, also, if you get a later release of wetkit, this should be fixed, and you should keep whatever .gitignore files have been added by wetkit in its own modules after this fix has been implemented:
- [drupal.org/project/wetkit issues - .gitignore rules prevent versioning wetkit instance](https://www.drupal.org/node/2379961#comment-9748279)
