### ISSUE TITLE
Deploy Content Types and Redirect Loop

### ISSUE THREAD

**Issue by kristremblay** [wet-boew/wet-boew-drupal#1785]
I have been trying to get the deploy module working to no avail.  I am able to create content of type `Deploy (simple)`, however once it is created I can only view it.  If I try to click `edit` or `delete` I get stuck in a redirect loop.

The URL changes from `/node/85/edit?destination=admin/content` to `/node/6a5745a8-fe88-4ed2-b430-f33fc7f4cd6a/edit` , if that helps at all, but I don't know if it would.

**Comment by kristremblay** [comment]
uuid_redirect seems to be where the issue is stemming from but I have no idea what this field should be set to.

**Comment by sylus** [comment]
So you have created both a src site and a dest site and set the endpoints correctly? The uuid_redirect module gets enabled so that the node/edit screens on production site are always redirected to the source site. The admin path is at: admin/config/search/uuid_redirect you might just need to change the value to the correct source site.

**Comment by kristremblay** [comment]
Good afternoon, Sylus, hope all is well.  As your response appeared, as is the fashion with posting a question to the internet after hours of brain-wracking...it donned on me that I've completely missed how Deploy works lol.  This is embarrassing.

**Comment by kristremblay** [comment]
While I've got you here...any idea why `DeployAuthenticationException: Authentication error: 406 Not Acceptable in DeployAuthenticatorSession->deploy()` keeps rearing its ugly head when I try to deploy a plan?

**Comment by sylus** [comment]
No worries! For the authentication issue this is because the default password for the endpoint isn't correct. You will have to go to: admin/structure/deploy and then select authentication under both endpoint and change the password from the default one. 

The screen for the in-memory endpoint for instance is at:

admin/structure/deploy/endpoints/list/destination_site_batch_endpoint/edit/authenticator

You can get a quick view of the current settings + displayed password at:

admin/structure/deploy/endpoints/list/destination_site_batch_endpoint/export

Make sure the settings are configured to the password on the prod site and correct endpoint url. With wetkit_deployment_destination enabled on that env.

**Comment by kristremblay** [comment]
Is it possible that the authentication could be failing because the password that was set on our test installation was too short etc?

**Comment by kristremblay** [comment]
ALSO...man there's a lot going on today.  I was having trouble for the longest time finding the drop down menu for deployment plans under content..it just wasn't there.

However, I noticed that the main menu ponits to `admin/content` and not `admin/content/node`.  If I go to the second one, everything is well in the world.  Simply clicking on `content` = no deployment options.

**Comment by sylus** [comment]
You shouldn't use either of those screens, I don't even think they should have been added to admin/content/node. In the 4.1 release the area was /admin/dashboard/deployment but in the dev and soon to be released it will be in /admin/structure/deployment.

**Comment by kristremblay** [comment]
Both of those paths take me to the Deployment section, however my issue is with adding items to deployment plans.  To add items to the deployment plan I need to do it through `admin/content/node` for some reason.

**Comment by sylus** [comment]
You should also be able to see it on the deployment section: admin/structure/deploy which is the screen for that purpose. There quicktabs at the bottom for deploying any type of entity. The vbo actions should also be there as well. "Manage entity in deployment plan"

**Comment by kristremblay** [comment]
Going to `admin/structure/deploy` shows me the two deployment plans and nothing else.

**Comment by sylus** [comment]
So you enabled wetkit_deployment_source on the source site? To get deploy enabled and all related modules?

**Comment by sylus** [comment]
This is v4.1? or latest dev?

**Comment by kristremblay** [comment]
Yes sir, and it is 4.1.  Sorry for the late reply.

**Comment by sylus** [comment]
Okay on 4.1 there is a screen at admin/dashboard/deployment. Do you see the quicktabs at the bottom of that page? (Source Site).

**Comment by kristremblay** [comment]
![deployment screen](https://cloud.githubusercontent.com/assets/7587183/12399585/25a5d5b4-bdd8-11e5-8e53-a05338e46327.PNG)

**Comment by kristremblay** [comment]
Is `admin/dashboard/deployment` supposed to redirect to `admin/structure/deploy` or do I have something wonky going on over here?

**Comment by sylus** [comment]
Yes it will in the dev version but for 4.1 your screen is correct. You can use that screen for deployments.

**Comment by kristremblay** [comment]
I just realized why new content is not showing up in that list:  If you leave the content as `Language Neutral` it does not come up.
