### ISSUE TITLE
Admin Content View Cannot Identify Entity Translated Content

### ISSUE THREAD

**Issue by mgifford** [wet-boew/wet-boew-drupal#1913]
Would be great to get an answer to this question https://www.drupal.org/node/2895706

**Comment by joejoseph00** [comment]
mgifford, this question was answered:
https://www.drupal.org/project/wetkit/issues/2895706

do not filter on content language, because you're field translating when using entity translation.  Instead, filter on title field language , this filter is provided by the title module and is built into the distro.

**Comment by mgifford** [comment]
Ok, thanks.
