### ISSUE TITLE
Drupal Grids

### ISSUE THREAD

**Issue by AlexCreamer** [wet-boew/wet-boew-drupal#1915]
Hi, I read I could come here with questions.
I'm using Drupal 7 with the Drupal distribution, https://www.drupal.org/project/wetkit, and I was wondering how to make grids. I have the following grid, http://alexcreamer.org/?q=en/content/grid-example, but it looks I'm doing something wrong since I'm not getting any grids.

**Comment by joel-osc** [comment]
Hi Alex, glad you are using the distro! I think there are some installation issues you may want to look at:
1. I would enable clean urls - to do so you need modrewrite enabled for php. There is a lot of information on drupal.org about this topic.
2. When I inspect element I see this error, which I think will be fixed by 1: Source map error: request failed with status 404
Resource URL: http://alexcreamer.org/sites/default/files/js/js_WkOMkSyjg9rxsesVK2mUAVX_dhZTWbIE6jpIzuL-ygM.js
Source Map URL: jquery-1.10.2.min.map
3. I am not sure what would cause this error: Warning: Parameter 1 to _wetkit_wetboew_libraries_get_version() but you can use dpm() (devel module) in the _wetkit_wetboew_libraries_get_version() function to see what is being passed to that function.

Cheers.

**Comment by AlexCreamer** [comment]
Hi Joel, glad to be using such a powerful distro! Concerning my grid problem, I tried the following Nginx configuration, https://drupal.stackexchange.com/a/60582, which is supposedly a solution for rewrites but I'm still not getting grids. I'm able to get all the requested js files though.
And concerning the warning, I'm not sure where the _wetkit_wetboew_libraries_get_version() function is so I can use dpm(), plus I'm not sure how to put dpm() (e.g., I'm not sure if I wrap the previous mentioned function with it).
Cheers.

**Comment by AlexCreamer** [comment]
I have disabled css compresion and it looks like I have a CSS file not used (utils-min.css) that is used by the example website. I'm not sure how to include utils-min.css on my site though.

**Comment by mxlav** [comment]
You might just be missing the proper css classes. Make sure all you divs have the appropriate classes
[http://wet-boew.github.io/wet-boew-styleguide/v4/design/grids-en.html](http://wet-boew.github.io/wet-boew-styleguide/v4/design/grids-en.html)

**Comment by AlexCreamer** [comment]
I tried following the css instructions on that page and am getting the same error. Is there anything better I can provide to make this easier and better?

**Comment by joel-osc** [comment]
I would recommend fixing clean urls first, as it is definitely not working. Not sure about nginx as we use apache.

**Comment by AlexCreamer** [comment]
Ok, I have Apache installed now and configured, and I have used `a2enmod rewrite` and did a service restart but I still see no grids.

**Comment by AlexCreamer** [comment]
I have even tried adding a chart http://alexcreamer.org/?q=en/content/chart-example

**Comment by joel-osc** [comment]
Still no clean urls. I would recommend using Acquia DevDesktop - it will give you a good stack and installation is easy from there.

**Comment by AlexCreamer** [comment]
Got my grids working. I was using the wrong css twice. The first time I was using http://wet-boew.github.io/wet-boew-legacy/v3.1/demos/grids/grid-base-en.html and the second time I was putting a `.` in front of the classes showed by mxlav's link. By removing the `.` I was able to get grids. Also, by following the WET classes instead, I was also able to get background colours. Thanks for the help. :)
