### ISSUE TITLE
Change CSS of a Block on a page

### ISSUE THREAD

**Issue by AlexCreamer** [wet-boew/wet-boew-drupal#1922]
Hi, I`m looking to change the CSS of a block on specific page. I`m using the WetKit omega theme.

**Comment by nathanv** [comment]
Hello @AlexCreamer . 
A disclaimer: https://www.drupal.org/project/wetkit_omega is currently unsupported and from a very old branch of https://www.drupal.org/project/omega . We did patch a security fix but that's it. We haven't kept it up to date otherwise. Use at your own risk!

Take a look at https://atendesigngroup.com/blog/adding-css-classes-blocks-drupal for some tips.
Use your debugging tools to identify variables that are specific to that page and then add the css classes selectively. Hope that helps!

**Comment by AlexCreamer** [comment]
Hello Nathan, thanks for telling me about WetKit Omega being unsupported.

I'm reading the page you told me to look at and I'm not sure how to implement the preprocess function. Does it go in my `profiles/wetkit/themes/wetkit_omega/templates/blocks/block.tpl.php` or in my `sites/default/themes/wetkit_omega/templates/blocks/block.tpl.php`?

**Comment by joejoseph00** [comment]
Hi AlexCreamer
put it in your sites/default/themes/wetkit_omega/templates/blocks/block.tpl.php
any module you copy into sites takes presidence over what is in profiles.

If you were using wetkit_bootstrap there is a way to create a subtheme on that.  I think omega also allows this but been a while since I used omega
