### ISSUE TITLE
Integrate Edit + Aloha Editor

### ISSUE THREAD

**Issue by sylus** [wet-boew/wet-boew-drupal#193]
Its time for a revolution in Editing. 

The Spark (http://drupal.org/project/spark) initative with Drupal is going ahead full force and they have released an initial working release of Edit (http://drupal.org/project/edit) using Aloha Editor (http://aloha-editor.org/) in its dev branch.

Basically this allows for anyone to perform realtime in place editing rather then needing to go into the backend.

This will likely take a few weeks to get in but wanted to get people excited about this :)

Aloha Editor will be the official WYSIWYG of Spark and perhaps even Drupal 8 Core!

To quote: Aloha Editor is the world's most advanced browser HTML5 based WYSIWYG editor lets you experience a whole new way of editing. It's faster than existing technologies and offers unprecedented WYSIWYG functionalities.

**Comment by joejoseph00** [comment]
Hi @sylus, we at CTA have tens of thousands of dollars of customizations invested in TinyMCE specific to government of Canada requirements.  Were you previously aware of our investments in TinyMCE ?  I will try to get a full spec of all the features of our version of TinyMCE.  Lots dealing with WCAG compliance, word copy-paste formatting cleanup and more.

I'd hate to have to re-hire someone to re-do all our customisations when they are working very well already in TinyMCE.  We can help you integrate our version of TinyMCE into the WetKit Drupal distro, as we'll be needing it here.  It should be possible to set up more than one WYSIWIG editor, it could be that there's other neat tools out there but for our internet website we'll for sure be needing Tiny.

**Comment by StephenOTT** [comment]
@joejoseph00, Lets get that spec out asap so we can start comparing against the editor.  I have started going over the code you provided to me a few days ago, but a spec that cta has paid for would be great.  I know we would love to see that document.

**Comment by colans** [comment]
@joejoseph00: Is your TinyMCE project publicly available?  As in, do you have a project page with code repository for it set up somewhere like [IRCan](http://ircan-rican.gc.ca/), GitHub, or drupal.org?  If so, please provide it so that we may review.  It would rather easy for us to support it here if we could keep it up to date by git pulling from your project repository.

This sort of subproject could be managed as a git submodule.

**Comment by StephenOTT** [comment]
Let's get a fork going for this.

**Comment by joejoseph00** [comment]
Our webmaster is preparing the latest specs document but it will take a couple days to prepare.  Meanwhile here is the actual code (see Readme for installation details) 
http://wet.7pro.ca/sites/wet.7pro.ca/files/tinymce.zip

as soon as I get the specs, I'll post them here.

**Comment by joejoseph00** [comment]
Still digging up the specs.  Hopefully have the specs today some time.

**Comment by colans** [comment]
How about a URL for the public-facing repo?

**Comment by joejoseph00** [comment]
http://wet.7pro.ca/sites/wet.7pro.ca/files/tinymce.zip 
will get you the code, I will get the specs asap.  Let me know if this link is not working for you.  I just tested it and it works here but I could put it somewhere else if you like.
As Stephen suggests, it's a good idea to make a git sub module, or feel free to make a git sub module using these instructions: http://git-scm.com/book/en/Git-Tools-Submodules   I am new to github so when I get a few spare cycles I'll do it.  Right now I'm scrambling to show my boss that I'm comming closer to finishing the PD feature/module that everyone else is going to need for their wet distro.

**Comment by joejoseph00** [comment]
here's the specs:  this spec was written by the developer of the customisations (Mike Block)  and describes his latest upgrades.  

TinyMCE Improvements
Upgrades to TinyMCE core package
The TinyMCE package was updated from version 3.3.8 to 3.4.9. Much of the change is for stability and interoperability with different browsers, but some changes are significant for the Agency (OTC-CTA).
• Correction to TFOOT placement: TFOOT was erroneously being placed at the end of the table, and needs to be located at the top of the table to be valid
• Added possibility to change properties of all table cells in a column
• Improved handling of MS Word content in paste operations to retain semantic structure while removing design elements
• Addition of WAI-ARIA components to improve the accessibility of the editor itself
• Improved list control for better flexibility in creating lists
• Inclusion of over 390 additional bug fixes and enhancements since version 3.3.8
Upgrades to WAS Cleanup Tools
The WAS cleanup tools were designed for a different CMS, but are applicable, for the most part to the Drupal installation of TinyMCE. This plug-in offers the following enhancements.
• Modular extension to Drupal. This does not affect a default Drupal installation and will not need patching moving forward to Drupal 7
• Quick Fix Utility, which does the following actions on the document:
o   removes empty blocks
o   groups numbers with &nbsp;
o   strips paragraphs from table cells where there is only one paragraph
o   aligns numeric data to the right (this prompts for confirmation, as it can override settings you wish to retain)
o   strips all references in tables for width and height settings
o   converts table alignments to styles (i.e. valign and align attributes carried in from word)
o   fixes other alignments in content and images, as well as stripping things like cellpadding/spacing and border
o   fixes a number of other small issues and also corrects footnote references
• Ability to demote or promote heading levels to create proper sequence from page title
• Creation of Table of Contents from document headings. This drops the TOC into a div with an id of “auto-toc” just after the cursor position. It adds all bookmarks to the headings and links TOC items. You can also choose to omit a heading from the index (ensure that this does not break the heading order to avoid errors)
• Addition of headers and id’s to tables. You need to mark the table with initial th/scope declarations, but then it can infer the relationships between the headers and cells. Some cleanup is required to ensure that id’s aren’t included beyond their logical scope point, but this greatly minimizes the effort of tagging tables.
• Adding TH/scope to documents can be accelerated with shortcut tools that process all THEAD sections to col or colgroup scoped headers. You can apply first column TH with row or rowgroup for tables as well.
• Selection Language can be set for language of parts compliance. This wraps the selected text with a span tag and includes the lang attribute. There is a Drupal filter that will ensure that xml:lang is added, as it’s not supported by TinyMCE.
• Other tools include changing text case for a range of text, stripping tables to text, processing acronyms (can add a custom one that’s not in the default agency list and replace throughout the document, with prompts).
Runtime Filters in Drupal
In addition to improvements to TinyMCE, the new Drupal module includes input filters that will examine common attributes and styles in tags and convert to standard CSS classes. This repairs most alignment in styles as well as replacing attributes like align, valign, nowrap, clear, border, etc. that are either deprecated and fail on validators or simply pollute HTML coding.
An additional filter will ensure that lang attributes are always matched with xml:lang attributes to ensure full XHTML strict compliance.

**Comment by joejoseph00** [comment]
We're currently using this version of TinyMCE in D6 on our internet site and D7 for our intranet site.  To get all the above functionality in TinyMCE probably cost us over $40,000 in contracting fees.  Why not use our version of TinyMCE instead of some pre-alpha editor that will need another year of debugging when we've got one that is stable and works.  Note: our version of TinyMCE is intended to be used by authenticated priviledged users only.  For external users we may want to have some really simple editor that has very few features so that we don't have to worry about security.

**Comment by sylus** [comment]
Hey @joejoseph00 thanks for sharing the tinymce code. I talked this over with a few people and am thinking for now we will integrate the work you have done with TinyMCE. We are still committed to integrating Aloha Editor as it is quite frankly better then TinyMCE + CKEditor particularly in performance, speed and the fact it does front end editing.

However it is alpha and will take more then a few months to reach feature parity with TinyMCE. So for v3.0 I think TinyMCE is the way to go.

Do you have some spare time this week to go over this with me, perhaps in person? Would greatly speed up integrating this.

**Comment by StephenOTT** [comment]
Great to see this moving forward.

**Comment by joejoseph00** [comment]
Hi @stylus and everyone else, in addition to the spec sheet I gave was detailing upgrades made to TinyMCE.  Here's a list of the other functions it has over and above the standard version of TinyMCE otherwise not noted in the upgrade spec:

---

Allows for using the heading styles h2 h3 etc to be used as a Table of Contents (TOC). You can convert all of them up or down a level (i.e. demote all levels demotes h2 to h3 and h3 becomes h4 etc.) The other controls allow you to customize the table of contents regarding which heading levels display.

<b>-Quick Fix All-</b>

---

<b>-Convert titles - </b>
- Demote all titles one level
- promote all titles one level
- Create TOC Here
- H2 Tags Only
- H2 and H3 Tags Only
- H2 to H4 Tags Only
- All Levels
- Hide heading from page index
- Show heading in page index

---

<b>\- Convert tables - </b>
- Convert Table to Text
- Convert All Tables to Text

---

These tools allow you to accessibly code tables by putting in thead sections, row headers, and ids when you need them. Highlight whatever cells you want to affect, then choose the option below that meets your need. Be careful with Ids and Headers - they're difficult to do correctly and require checking afterwards to make sure they're right.

<b>Table Headers </b> -First row column headers
- THEAD sections column headers
- First column row headers (active table only)
- First column row headers
- Add ID's and Headers to table

---

<b>Change Selection Case -</b>
- Uppercase
- Lowercase
- Sentence Case
- Title Case

---

This was designed for a database of saved terms so it could go through and replace each instance of the acronym with the <acronym title = ""> tags. It's not properly integrated in Drupal.  However, this is now unnecessary, as we are now using a Drupal Module for Acronyms instead. 

Process Acronyms - Process saved list of terms
- Prompt for term and replacement

---

Allows you to specify a piece of text within the content as a specific language. (i.e. the word "français" in the middle of an English page)
<b>Set Selection Language</b>
- English
  - French

---

<b>-Other tools-</b>
Other Cleanup - Remove empty h# and p blocks
Remove table width/height settings
Remove table width/height settings (active table only)
Convert cell alignments to styles
Right-align numeric data cells
Join Groups of Numbers

**Comment by joejoseph00** [comment]
TinyMCE's website shows that it has a working french translation complete to 100% http://www.tinymce.com/i18n/index.php?ctrl=lang&act=download&pr_id=1 but we didn't include this in our version.  (?) 
I would like to remedy this situation before we move our internet site over to D7.  Luckily it appears most of the work is done, there's a language file available, but it needs to be tested to see if it works with the customisations and with the drupal module.  At that point I could add in the language file for the WAS customisations.  In fact, the name WAS should be changed to WET-BOEW, as WAS is an ackronym for the old CMS we ran before D6.  We just never changed the WAS button to anything else.  It's just an image file, should be easy enough to change.  So a few things to do, but this version of TinyMCE has a LOT of customisations as you can see.

**Comment by sylus** [comment]
Hey sorry for not getting back to you earlier, are you able for early next week :) Hopefully can get this in by mid week.

**Comment by joejoseph00** [comment]
Communications depts everywhere will especially like the MS Word button that cleans content copied from word making it html 5 compliant and clean as a whistle.  So we should make sure to enable this feature by default.

**Comment by joejoseph00** [comment]
@sylus, Please let me know what the status of this TinyMCE to WetKit Distro is, I've got translations for the extended plugin features ready to go in, I just need a place to put them. Was going to fork whatever you have and then test it.

**Comment by joejoseph00** [comment]
Hi @sylus, the additional translations are ready for TinyMCE http://wet.7pro.ca/sites/wet.7pro.ca/files/libraries_tinymce_jscripts_tiny_mce_plugins_wascleanup_langs.tar.gz
  Once integrated into the wet-boew drupal distro I will test both english and french and make sure the translations make sense and work.

@StephenOtt Special thanks to the city of Ottawa for the translation work.  I then took your translations and put it into the corresponding js files required for the wascleanup features.  

   In the translation files you will see that I refer to the wascleanup as WET-BOEW cleanup and so I changed the language files for this naming.  We'll want to change the WAS button as well to a WET-BOEW button for example.  

Thanks,

**Comment by sylus** [comment]
Initial port has been committed and works pretty smoothly. Also made it so tinymce will detect the native language and switch accordingly. All french translations have been added as well. Take a look! Please post more recent issue with WYSIWYG in the meta issue #270
