### ISSUE TITLE
Where should we put custom .tpl files and css?

### ISSUE THREAD

**Issue by dsamojlenko** [wet-boew/wet-boew-drupal#201]
If we're looking to customize .tpl files beyond what's in the distro, where is a safe place to put them so that they won't be overwritten in a future update?  For example, in our case we want to create a custom look for blog pages so we've created node--blog.tpl.php and page--blog.tpl.php files.

Should they just go directly in the profiles/wetkit/themes/wetkit_adaptivetheme/templates folder?  Or is there a safer place for them?

And on a related topic, if we needed to add custom styles for these .tpl files (or any custom styles for that matter), where should they go?  I've just been adding a custom styles section at the end of /profiles/wetkit/css/wetkit.css, but I presume they'll be overwritten next time I update.  Is there a safe place to add custom styles?

**Comment by sylus** [comment]
1) All custom tpl could potentially go into: profiles/wetkit/themes/wetkit_adaptivetheme/templates/custom though it is pretty open ended
2) For custom styles what I would do is:
a) in wetkit_adaptivetheme.info add a new css file (just like wetkit-adaptivetheme-custom.css)
b) create a corresponding file in sass if you wish to use sass type logic (just like wetkit-adaptivetheme-custom.scss)
c) if you don't have a corresponding sass file the css file will never be rewritten, otherwise the css file will be generated from sass.
