### ISSUE TITLE
Organizational Chart Generation

### ISSUE THREAD

**Issue by StephenOTT** [wet-boew/wet-boew-drupal#254]
Anyone play with Organization Chart Generation in Drupal?

Been looking at a few outdated modules, but nothing stood out

Been thinking a import of data and using Google Charts/Visualization: https://developers.google.com/chart/interactive/docs/gallery/orgchart

**Comment by StephenOTT** [comment]
@mgifford Seen any accessible options?

**Comment by mgifford** [comment]
Do you have examples of what you're trying to import?

Which are the org chart modules you've been looking at?

I haven't heard of any accessibility initiatives any of them.

Interesting that they've chosen to develop the output as a HTML table.  That and not a particularly semantic one.

http://vagrantup.com/v1/docs/getting-started/index.html

I think ideally you'd have:

Mike
  -> Alice
  -> Jim
    --> Bob
      ---> Carol
    --> John

That could build out a pretty SVG image based on indented text.  

Maybe that's too simplistic though.

**Comment by StephenOTT** [comment]
Something like:
- http://ottawa.ca/en/city_hall/policiesadministration/charts/index.html

**Comment by StephenOTT** [comment]
Specific data could look like:
Name, Reports To
Person A, NULL
Person B, Person A
Person C, Person A
Person D, Person C
Person E, Person B

**Comment by StephenOTT** [comment]
Some Federal Examples of Charts out there:
http://www.tc.gc.ca/eng/aboutus-department-menu.htm
http://www.tbs-sct.gc.ca/ocg-bcg/abu-ans/chart-organigramme-eng.asp
http://www.tc.gc.ca/eng/marinesafety/about-us-org-813.htm
http://cas-ncr-nter03.cas-satj.gc.ca/portal/page/portal/CAS/orgchart_eng
http://www.fja-cmf.gc.ca/fja-cmf/structure-eng.html
http://www.csis-scrs.gc.ca/bts/rgchrt-eng.asp
http://www4.agr.gc.ca/AAFC-AAC/display-afficher.do?id=1174311378019&lang=eng
http://www.ahrc-pac.gc.ca/v2/aaa-app/wwa-qsn/structure-structure-eng.php

Can see that many use an image and then provide the same information in bullet lists below the chart

**Comment by sylus** [comment]
Could we maybe talk about extended and integrated with the charts from WET?

Could add a plugin that adds the relevant information through javascript using Drupal.settings?

Simple Charts: http://wet-boew.github.com/wet-boew/demos/charts/simple-eng.html
Complex Charts: http://wet-boew.github.com/wet-boew/demos/charts/complex-eng.html
Organizational Charts: start work for next version?

Obviously the organization charts are not there but might be an idea that @pjackson28 would consider.

**Comment by joejoseph00** [comment]
No simple answer to Organizational Charts.  I played a bit with OrgPlus 9, consuming csv datasets generated from our HR database (one english and one french) I was able to quickly and fairly easily create a PDF org chart (with titles, hierarchy) which we then could post as a link on our intranet site but we don't publish this stuff to our internet site.  But I don't know how accessible PDF's are for blind people, in fact, I don't think Blind people appreciate org charts anyway because they tend to be visual in nature.

I imagine that the feeds module could be used to turn this type of data into nodes but from there I'm not sure if views would be able to make org charts, it might take a custom code, or if someone that is a total drupal guru might tell us how else this could be done the drupal way, otherwise it could mean writing a custom module of some kind.

**Comment by mgifford** [comment]
With both maps & other visual elements it's mostly about understanding the task that a user would be trying to accomplish. With an org chart it's all about relationships. Being able to search by position or name & find out who they manage or manages them.  

It's knowing that there's a senior management team of five positions that are roughly broken down into distinctive roles.  

Why do people want the org chart?  What purpose it serves for the organization can be very specific.

**Comment by StephenOTT** [comment]
In most examples provided, if not all other them, the org chart is about showing, as you said, the relationships within the organization and who reports to who.

**Comment by sylus** [comment]
Can reopen this issue later but for now more pressing issues ^_^
