### ISSUE TITLE
(META) Mutilingual

### ISSUE THREAD

**Issue by sylus** [wet-boew/wet-boew-drupal#267]
This is a catch all issue that I can use to reference from other issues.

**Comment by sylus** [comment]
I am consistently trying to prevent module creep but it looks like there are a few that have to be added:

http://drupal.org/project/i18nviews
http://drupal.org/project/entity_translation
http://drupal.org/project/transliteration
http://drupal.org/project/title
http://drupal.org/project/i18_page_views

Please note for title and entity_translation they will only be working with fieldable_panel_panes and pure entities till node problems have been resolved.

Can I get some other people to confirm the list before I go ahead and start work on this? @mgifford @joejoseph00  @joel-osc

**Comment by mgifford** [comment]
Does seem a bit silly. Back in the day it was much simpler.  Transliteration is definitely important. I'll get back to you on the others.

**Comment by joejoseph00** [comment]
As for issues with i18n, sorting a translated taxonomy is a sore spot.  And workbench and i18n is apparently a "work in progress".  We were talking about workbench the other day, and if it comes down to choosing the UOttawa side-by-side interface vs workbench, our users would probably choose the side-by-side UOttawa interface.

UPDATE:  Since taking a training course on multilingual site building, we have some better documentation on this subject.  I'm not sure how much of the documentation I can share as it was written by Evolving web, but it appears that Evolving web wrote this documentation for Acquia.  I recommend the course to others.

**Comment by RobJohnston** [comment]
I note here that the translation module just creeped in on issue #474.  Strike one from the list above.

**Comment by joejoseph00** [comment]
Hi @robjohnston do you mean transliteration module?    Also, what do you mean by creeped in on issue #474, and strike one from the list?

**Comment by sylus** [comment]
Yeah @RobJohnston mean transliteration, and correctly wrote that once less to deal with in comment 1 from #474 ^_^
