### ISSUE TITLE
WetKit Apps install Failing - SQL State error

### ISSUE THREAD

**Issue by StephenOTT** [wet-boew/wet-boew-drupal#339]
Getting the following error when apps try to install during site setup:

SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'public://apps/wetkit_admin_logo_3.png' for key 'uri'

Also all of the apps are unchecked during install except for the Demo app.  Is this expected behaviour?

**Comment by sylus** [comment]
This is expected behavior for only Demo app to be checked. As for the duplicate entry it seems you are reinstalling to the same directory. This is close to being fixed but right now is a symptom of apps being installed locally.

Fix should be coming out in a day or two.

Does the install still work overall?

**Comment by StephenOTT** [comment]
No the install cannot be completed.  Cannot get past the Install apps even if you skip page.

You can enter the site, but the WET theme is unavailable/not installed and obviously most of the WET options+config are not there because no apps.

**Comment by sylus** [comment]
Yeah this is definitely related to title module I'll disable it in next commit. Give me an hour or so. _Doing translations you sent to me now_

**Comment by StephenOTT** [comment]
Dont think there is a rush.    Just something for people to be aware of if they try installing over the next few commits.

**Comment by sylus** [comment]
Fixed!
