### ISSUE TITLE
Process for using Panopoly as base distro

### ISSUE THREAD

**Issue by timwood** [wet-boew/wet-boew-drupal#357]
Can you explain or provide documentation of the process for using Panopoly as the base distro and how you keep updated with improvements from Panopoly over time? We are evaluating Panopoly for the same exact purpose at The US Department of Commerce along with Adaptive Theme!

**Comment by sylus** [comment]
Hey @timwood it is great to hear from you!

I can say that Panopoly does provide a great base for a custom distribution! It is bar none in my honest opinion the best Drupal distribution out there. Also Drupal 8 will be aligning itself with the work done in Panopoly. If you watch the DrupalCon Munich Layouts lecture where they compare the various way to manage content, the layout initiative leader from Drupal.org explicitly said that Drupal 8 will be following Matt Cheney's (@populist) method.

The main caveat for us is that we require control over all our modules so we had to change the namespace so as to minmize any potential conflicts or changes in the upstream code in the future. There are a few workflows + scripts we use but in the end we usually evaluate commit by commit from Panopoly the stuff we want to merge in. In addition we have a strict multilingual requirement so that is another further wrinkle we have to deal with along with a few other minor deviations to the panopoly code. 

However I do know @populist is consistently working on improving panopoly so it works great as a base distro perhaps without requiring to change the namespace. There is a guide for this at: http://drupal.org/node/1651128. We are currently debating the merits of this but for the immediate future looks like we will just by syncing commit by commit (though not sure if this is the right call but have to follow mandate given). You will note that for each of our submodules we have a readme which says to which recent commit we are synchronized with.

As an aside though @populist (Panopoly) and @ Jeff Burnz (AdaptiveTheme) have both created an amazing base distro and theme that work great in tandem together. They are also extremely approachable and have provided a great amount of assistance while we are working on our distribution for Government of Canada. You will certainly not regret using both those technologies. I also have to say I was extremely pleased with AdaptiveTheme and its extensibility and love that we completely validate with HTML5 with minimal effort. Though our WETBOEW jQuery and Markup we base our Drupal install on heavily assisted with that: https://github.com/wet-boew/wet-boew and http://wet-boew.github.com/wet-boew/docs/index-eng.html (html). The work in Panopoly is self evident and too many features to list here! ^_^

I would love to keep in contact with you guys as you are working on this as perhaps there are areas where we overlap :) We will be in close contact with the US in our Open Data discussions.

Please let me know if you require further clarification or have any more questions. The work you guys are doing with Open Source in the US is nothing short of inspirational :)

**Comment by sylus** [comment]
Closing for now please reopen as needed :)
