### ISSUE TITLE
Improvements to Build

### ISSUE THREAD

**Issue by sylus** [wet-boew/wet-boew-drupal#392]
Hey @patcon, though I would create an issue here where we could discuss better methods for the built. It does work right now with pull requests so at least that is in :)

What possible improvements were you considering?

**Comment by patcon** [comment]
You know what, I've just seen little pieces of how things are done in other PR's, but I need to go through and check out the current state. I'll do that soon, before I make any suggestions :)

EDIT: Actually, right before I read this, I started issue #394 that deals a high-level concern. Maybe leave that one for that, and retitle this one to be about improving build reproducibility? (ie. dropping as many unpinned references as possible, for starters)

**Comment by patcon** [comment]
Maybe we should touch base on this:
https://github.com/wet-boew/wet-boew-drupal/wiki/Frequently-Asked-Questions#wiki-How_do_I_keep_Drupal_up_to_date

*Note: I typed all this out and realized there was still more to clarify. Think we could do an IRC or skype chat? There's a whole bunch of assumptions we should probably talk through

Depending on how the build is happening, I would think we would try to encourage people upgrading modules by upgrading the install profile, rather than diverging from the established codebase.

Not sure how much you've considering [inheritable install profiles](http://drupal.org/node/1356276), but I'm thinking maybe that would be how we'd want people to extend -- build on top, and treat the wetkit profile as an immutable thing that sits underneath and is kept in sync with the official profile releases? (Sorry if that link is old news. I've forgotten if it's come up in the wetkit issue queue :)

**Comment by patcon** [comment]
Also, I'm wondering whether what the pros and cons of moving away from scattered makefile might be. The overhead is greatly reduced with just have a single one, but I don't understand the restrictions of apps, so I'm guessing it might have something to do with that

**Comment by sylus** [comment]
Hey @patcon what is your skype? ^_^

**Comment by patcon** [comment]
skype: patrick.c.connolly

**Comment by sylus** [comment]
Moving issue to #400
