### ISSUE TITLE
multisite

### ISSUE THREAD

**Issue by mxlav** [wet-boew/wet-boew-drupal#397]
I've been trying to setup multisite with the sites.php and haven't been successful. I was wondering if anybody has attempted this. I want to accomplish this without playing with the host file or Vhost since i won't have easy access to these files once i get the a server.

I'm running XAMPP on W7.

My folder structure looks like this

<pre><code>cbsadrupal/sites/default
   default.php
cbsadrupal/sites/itam
   default.php
cbsadrupal/itqm
   default.php
</code></pre>

my site.php file looks like this

<pre><code>$sites['localhost/cbsadrupal'] = 'default';
$sites['localhost/cbsadrupal/itam'] = 'itam';
$sites['localhost/cbsadrupal/itqm'] = 'itqm';
</code></pre>

Any help would be appreciated.

**Comment by RobJohnston** [comment]
Hi @mxlav, it's been awhile since you asked and we've recently set-up multisite.  Haven't noticed any problems, but we're still migrating content into the system.

I think that the folder structure is fine but the files named "default.php" should be "settings.php".  Your "site.php" file should be "sites.php".  

One neat thing we did, because we have a dev->testing->staging->production environment was to write the sites.php file thusly:

<code>
$sites = array(
  'itam.maintserver' => 'itam',
  'itam.testserver' => 'itam',
  'itam.staging' => 'itam',
  'itam.gc.ca' => 'itam',
  'itqm.maintserver' => 'itqm',
  'itqm.testserver' => 'itqm',
  'itqm.staging' => 'itqm',
  'itqm.gc.ca' => 'itqm',
)
</code>

That way we can easily compare the folders ('itam' and 'itqm' in your case) between servers with an existing tool.  Be sure to include all the English and French variations of the .gc.ca URL that the site can respond to.

**Comment by mxlav** [comment]
@RobJohnston, I've managed to get everything working locally with Vhosts and and defining my domain in the local hosts file etc etc, BUT one issue i'm having is when attempting to access remotely (my.ip.address/mysite1). My resource references are not being rewritten in Drupal to URLs that put you through the reverse proxy to the correct site.

Apparently Drupal has possible issues with reverse proxy'ing... a description of the problem here http://drupal.org/node/244593

I've gone seperate install for each site... for now so I can move forward with my prototypes, but ideally I'de like to get dev and prod (at a minimum) set up for multisite.

**Comment by sylus** [comment]
Cleaning up some old issues. :)
