### ISSUE TITLE
simple_gmap in distro

### ISSUE THREAD

**Issue by mgifford** [wet-boew/wet-boew-drupal#432]
I've got nothing personally against Gmaps, but I thought that the GoC had a problem with it in general because it associates with a specific company (Google).

I pulled down a fresh install and saw that:
http://drupal.org/project/simple_gmap

I'm not sure yet how it's used, but probably isn't ideal for federal sites.

**Comment by sylus** [comment]
It is included as part of panopoly_core. I can add a patch that removes this like simplified_menu_admin but there are also a few hooks and other misc functions that would have to be removed from panopoly as well making this tricky.

**Comment by RobJohnston** [comment]
I think it was frowned upon because Google wouldn't provide French tiles (but I hear they are available, possibly originating from NRCan).  Also, some sites had privacy statements that said they didn't use cookies but were then caught (about 2 months ago) because the maps use a cookie from Google.  Twitter has the same problem.  Maybe there was a fear that this was a tracking cookie too?  Not sure.

Also, there are some GoC sites that get an exemption from the CLF and can use almost anything.

**Comment by sylus** [comment]
Is useful to keep in for non GoC.
