### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by liquidcms** [wet-boew/wet-boew-drupal#446]
I think somewhat mixed acceptance at the Sept 25 meet that a Roadmap was a critical missing component to the success of this project. And even though i don't see a lot of traction for this idea; i can't really blame anyone if i don't at least try to start the discussion.

an attempt to paraphrase from the meeting:
- as per discussions on the WG meeting on the 25th; many people felt that a roadmap was key to the success of this project
- the roadmap should list "features" (not to be confused with drupal Features) which those in the group (or outside the group?) feel are essential to this distro
- this map should highlight such feature aspects as priority, status, 18n aware (see future post on acceptance criteria), who is interested, who is working on it, delivery expectations, etc
- any level of a feature should be able to fit on to this map. for example i18n, mobile, wet, workflow are pretty high level features; whereas specific wet plugins, specific fields, etc also should have a place on this map - as Will had mentioned WET is integrated; which at a high level is a decent statement to make; but it is not "fully" integrated as many wet plugins are not in place yet (and, more to the point of the roadmap; maybe not all of them are even required)

There was a lot of discussion as to how to coordinate the info that goes with this roadmap. Many seemed to think github is the be-all-to-end-all for issue tracking; but i don't see how it can present this info properly. Clearly a g-doc spreadsheet is a much better format; possibly with links to specific issues here. I would certainly set this up if anyone confirms the need for a roadmap for this project.

**Comment by StephenOTT** [comment]
Thanks for Posting @liquidcms !!  There should a roadmap, I think we were all in total agreement with you.

I have been working on this the past few days.  The delay to posting these docs have been because we wanted to get the Github usage for tracking, like we talked about in the meeting, to show the roadmap using gihub.  This is getting close to being done.  At the same time the first draft of the list is being done in spreadsheet form, so as soon as that is ready to be shared I can put it out as a g-doc until the gihub side is set up.  I see it being over the next few days.

In the meantime, @liquidcms if you would like to post a listing of features that you see are missing or incomplete in the latest version of the distro, that would be greatly helpful.  Always beneficial to have more eyes reviewing code and functionality.

**Comment by liquidcms** [comment]
Hey Stephen, interested to see what a github version of s spreadsheet looks like.. :)

as for feature set or status i am not sure i'd be the best to comment (certainly on the first of these) as i am not likely to be an end user of the distro. I would think the RCMP, CTA, Health Canada, PWGSC, NRCan, City of Ottawa, etc, etc would be much better  to comment. But from what i heard from my clients as well as others, i could take an initial stab at it:
- clf3 - accessibility
- wet plugins integration (likely needs to be plugin by plugin as i am not sure everyone has a need for all of the plugins that the TBS includes in WET and i don't think the distro currently integrates all of them)
- bilingual support - i assume this is first and foremost for Canada; despite mention that other governments have shown an interest. this likely needs to be decided up front as there is a difference between fr/en, bilingual and multilingual - for instance i took a quick look at OttU's split editor and it is hard coded for FR/EN. This likely raises the idea i mentioned above of "acceptance criteria". not sure if the project is far enough along to formalize an acceptance criteria; but seems like if app stores are being looked at it would make sense. i would have to assume i18n capable would be an obvious criteria; an example would be the TableField module which is currently in the distro. This is a very cool and handy module that is painful as hell to do with other off the shelve modules. But it is currently not translatable due to significant limitations in the FieldAPI and i18n (many other field modules are also not translatable).
- wysiwyg - perhaps this also needs to be expanded to specific tools; the CTA tool set is useful, what about img insertion, direct linking to content, video insertion, maybe wiki tools, there is a quite a slew of plugins available here - but again should be driven by need rather than what can be done or what is available.
- workbench type function - workbench idea is pretty simple, allow a draft to be worked on and reviewed while original stays published and untouched. unclear why this got dropped.
- proactive disclosure module
- event calendar - including location field and map support
- discussion forum
- content parse and import - sounds like OttU is working on this? i think enhancements to the Migrate module? not sure. I have used the import_html module with a lot of success; but i'd assume OttU's work is more advanced.
- org charts
- members availability calendar (not sure how widely required this is for GoC; we did a pretty decent solution for the CTA)
- job postings
- search: solr seems like the way to go here but a lot of sub-features for search: facets, document search (i.e. search within documents), fuzzy search, etc
- mobile happy
- browser support.. ughhh.. what is the goal here? ie7, ie8 - likely need to state full spectrum of compliant browsers and again, should be driven by requirement; not what can be done - CTA states they are only allowed to use ie7; i think i have heard someone from the GoC state ie6 (but i assumed they were joking).
- social net? is this important to GoC?
- document management - so many options here
- user profiles, user dashboards, custom user experience etc - likely more for Intranet.
- content subscriptions
- newsletter

I am sure this is just scratching the surface; hopefully others will add (and remove) from this list. But, gotta have a list!! :)

**Comment by strinh** [comment]
Not sure if you guys might be interested, but there's definitely some roadmapish type stuff going on in the uOttawa github.  

For example, for the SiteCopy (Migrate) module, you can see the planned enhancements here: https://github.com/uottawa-wcms/uottawa_migrate/issues/5

For the Dual Language Editor, we haven't posted a roadmap, but I can tell you that we are planning to 
1. Decouple languages so that it isn't EN/FR but Primary/Secondary (6 mo out) with a plan to support more than two languages probably about a year out (shhhhh, don't tell Robert, he doesn't know this yet).
2. Plan to support Entities within the next 6 mos
3. Integrate the new WET Content Filter View within our custom admin view (side-by-side).

For Secure Syndication, see roadmap here:
https://github.com/uottawa-wcms/secsyn/issues/3

Those are the big things we are working right now.  We'd love to get everyone's feedback as we're continually improving our stuff (Peter, your feedback up above is especially useful to get a feel for what the community needs are). 

We'd also love to roll this up into a larger roadmap as we have smaller widgets we are working right now and foresee many more widgets/apps coming to light in the coming 6-12 months.

Sang

**Comment by StephenOTT** [comment]
Sorry for the delay on this stuff.  My fault.  I have been sick, and just getting over it in the past day.

**Comment by liquidcms** [comment]
if you are closing this; could you include a link to the roadmap? did that ever happen?

**Comment by StephenOTT** [comment]
Going to reopen because this still needs to be done

**Comment by liquidcms** [comment]
i think this is going to grow beyond what g-doc can handle but still seems like the right place to start with it. and by grow i think it will grow in both dimensions. i added a starting list above and Andrew suggested adding the list they specifically have for StatsCan requirements; but i think the direction we haven't listed is the columns for this. 

as a start, possibly these:
- feature
- under active devel
- who is working on it
- release status (date?)
- is it currently covered in the distro (maybe a code to state something like covered by addon modules not intended to be included in distro)
- does system level doc exist
- who is working on docs
- who wants it
- priority

i am sure i missed a few obvious ones and guessing this will grow as well as the feature list
