### ISSUE TITLE
Table Accessibility Best Practices

### ISSUE THREAD

**Issue by mgifford** [wet-boew/wet-boew-drupal#451]
Had a good back/forth with @pjackson28 on email & wanted to bring it here to see if we can move to some resolution about it.  

It's basically about adding better semantics to tables in HTML5. I'm not sure at this point what AT has good support for the scope attribute, particularly now that it can only be used with the TH tag.

The best solution would probably be a hybrid where you have a good default that covers most cases and then provide options to cover the rest.  This will be a challenge though to bring into Views, although it could be brought into this Distribution more easily. 

A header row with scope="col" is what I suggested here:
       https://drupal.org/node/864006#comment-6459764

Ideally in building a table the author would be able to specify whether a cell is acting as a header or not, but that the default would follow common assumptions (like the first row of TH elements are all have scope="row").  There are other things that it would be beneficial to be able to control through the Views interface that is likely beyond the scope of what is possible here.

I've proposed some ideas here for D8:
    https://drupal.org/node/1645308

Ultimately for this project it might be best to just make the changes in views-view-table.tpl.php

**Comment by duboisp** [comment]
My proposal to the HTML5 WHATWG may can help. [Proposal: new Table Parser Algorithm - new Table API - removal of the headers attribute - removal of the scope attribute](http://lists.whatwg.org/htdig.cgi/whatwg-whatwg.org/2012-September/037475.html)

@mgifford I will get back once I read all the related documentation.

:-)

**Comment by duboisp** [comment]
@mgifford to be able to help you I would need some information
- Script location (source code) of views-view-table.tpl.php
- A output sample of the most complex and simple table that would be handled by the function [theme_table](http://drupalcode.org/project/drupal.git/blob/HEAD:/core/includes/theme.inc#l1865)

When is possible, I would recommend, for simple table, to don't have any scope attribute and id/headers attribute. When the table just have simple column grouping and simple row grouping then use the scope. And for all the others situation use the id/headers attribute. That is in the perspective of the current [HTML5 4.9.12.2 Forming relationships between data cells and header cells](http://dev.w3.org/html5/spec/attributes-common-to-td-and-th-elements.html#header-and-data-cell-semantics) algorithm and to be conform to WCAG 2.0 Level AA. 

:-)

**Comment by mgifford** [comment]
I haven't really pushed the API.  For the most part the tables Drupal produces are pretty simple.  I haven't seen people try to publish more complicated tables.

Probably best (in the long term) to look at Drupal 8's theme_table():
  http://api.drupal.org/api/drupal/core!includes!theme.inc/function/theme_table/8

But yes, if it's clear that simple tables don't benefit from id/headers and complex tables are described as tables with nested sets of information...  With HTML5 4.9.12.2, neat to see them using algorithms.  Hadn't seen that via the W3C before.  

So then for HTML5 all we have to do is deal with complex tables and otherwise TH's will be fine.  That sounds logical.  

EDIT: Would be nice if the js WET table validation tool spit out a note that encourages folks with simple tables to  not make them more complicated (and heavy) than necessary.

**Comment by duboisp** [comment]
@mgifford 

Now the [HTML Table Validator](http://wet-boew.github.com/wet-boew/demos/tableparser/validator-htmltable.html) choose the best accessibility enhancement depends if is a simple table, a simple grouping table or a complex table.

Thanks for the link to the Drupal 8's theme_table(). It's funny to see the support for the column grouping, as described for styling purpose, but no support for any row grouping. The way the column group is presented, explained, that can be seen as a non-conformance to the [WCAG 2.0 - Level A - 1.4.1 Use of Color](http://www.w3.org/TR/WCAG20/#visual-audio-contrast-without-color). 

If you are looking to use the scope "col" and the scope "colgroup" when the table column is defined with two row, the headers cell (TH) that would be use to contain the scope "colgroup" must be anchored in a colgroup element, as described in the [HTML 5 specification 4.9.10 The th element](http://dev.w3.org/html5/spec/the-th-element.html).

> The colgroup keyword, which maps to the column group state
> The column group state means the header cell applies to all the remaining cells in the column group. A th element's scope attribute must not be in the column group state if the element is not anchored in a column group.

I think that would be harder to detect in the current Drupal 8's theme_table() function as it is currently coded because there is no explicit relationship defined between the colgroup and the headers cell (TH). And the question is what the theme_table() function would do if that is not conforming ?

Please let me know when you would have an output sample of the most complex table generated from the theme_table() function.

:-)

**Comment by mgifford** [comment]
That's useful. Thanks for the details. It will be something that we should look at, especially when we have some examples.
