### ISSUE TITLE
Mega Menu Quick Delete - Copy

### ISSUE THREAD

**Issue by lpgascon** [wet-boew/wet-boew-drupal#455]
Is there any way to quickly delete de Mega Menu items (using the databse or something?)

Is there also a quick way to copy all Mega Menu items from one wetkit install to another (without having to recreate all items individually)?

Thanks

**Comment by sylus** [comment]
Hey @lpgascon I can mention what we at stats can are doing. Basically we created our own feature (module) that deletes the existing mega menu and adds our own specific content to the mega menu. This works great because the mega menu is stored in code so for every Drupal Site we launch with Drupal-WET we have our own menu systems automatically in place.

Would it be beneficial for me to post a stripped down version of this code?

**Comment by lpgascon** [comment]
stripped down code would be greatly appreciated. Thanks

**Comment by kavinay** [comment]
+1.I'd appreciate a look too @sylus, thanks.

**Comment by sylus** [comment]
Should be up in a day sorry for wait.

**Comment by lpgascon** [comment]
No problem W
Whenever you have the time.

**Comment by StephenOTT** [comment]
Anyone take a look at: http://drupal.org/project/menu_import  ?
Has Drush support.

Have not tried it yet.  But looks like what you are trying to do.  Whether manually or through drush

**Comment by sylus** [comment]
Yeah menu_import is totally the way to go with this and great that it can create stub nodes based on a menu information architecture. This module can also wipe out an existing menu so solves this issue.
