### ISSUE TITLE
HTML5 Markup and TinyMCE

### ISSUE THREAD

**Issue by uottawa-wcms** [wet-boew/wet-boew-drupal#530]
Anyone have any luck making HTML5 markup (article, section, aside, figure, figcaption, etc) work with TinyMCE? Out of the box, it's stripping those tags out. Adding them to the filter is not working.

**Comment by theadbo** [comment]
We ended up abandoning tMCE for that very reason. Tried rolling a few of our own solutions but couldn't find good solution that didn't involve a complete re write (balancing our limited dev resources with need to GTD). Our content team is using an open source windoze editor (might be notepad++ or something like that) for marking up the content and then copy-pasta'ing into the bread and butter body text field. Some of the more advanced users I think are using the [It's all text](https://addons.mozilla.org/en-US/firefox/addon/its-all-text/) add on to smooth out the transition.
- edit: should have prefaced this with the timeframe. this was over a year ago so the reasons we forgot about tMCE may not be relevant anymore. Also, it may have been that it was putting stray p tags into the content, it's been a while since we were working on that ;-)

**Comment by uottawa-wcms** [comment]
I guess CTA's rewrite of TinyMCE didn't include HTML5 markup?

**Comment by uottawa-wcms** [comment]
Also, the TinyMCE editor officially says they support HTML5 via the schema property: http://www.tinymce.com/wiki.php/Configuration:schema, so I'm not sure what rewriting would have to be done? Shouldn't it just need configuring to set the schema to html5 instead of html4?

**Comment by sylus** [comment]
Please see Pull request #532 as includes some fixes, including updating tinymce to 3.5.7 to support HTML5 schema.

We will likely have to include more tags for wysiwyg filter not to strip out. But tinymce should at least not be stripping these tags anymore. I have checked and confirmed that article works.

@theadbo did adding the html5 schema attribute not work for you?

**Comment by sylus** [comment]
Notifying @StephenOTT and @openplus so are aware that tinymce can support the new tags.

**Comment by StephenOTT** [comment]
will incorporate into City version?
