### ISSUE TITLE
Blocks Everywhere.. :)

### ISSUE THREAD

**Issue by liquidcms** [wet-boew/wet-boew-drupal#549]
Just wanted to comment on a small comment Will made at last WG meeting when he frowned on the use of Blocks; sort of suggesting the idea of Blocks was passe. I haven't yet used Panopoly but i am a huge fan of Panels; but i tend to use a combination of Panels and Regions; not sure if Panopoly does the same or not but from the tag line "panels everywhere" i would guess that it doesn't - this idea has issues.

Please note that above i said "panels and regions"; not "panels and blocks". I think, but could be wrong as i haven't used Panolpoly; but even though Will commented on the use of Blocks; i would guess what he is really commenting on is the use of Regions. The way Panels works is to basically replace your site's Regions and use a single Content region which it then manages the layout for. The extent that you take this "region replacement" to is up to the theme/layout designer. For many designers leaving in such regions as footer, header, left, right and simply allowing Panels to "override" the Content region is a very usable alternative to what i suspect panopoly does; which is replace ALL regions with a single region.

The downside to "panels everywhere" is obvious OR it A. should be or B. there is a solution to this that has escaped me. Regions are (or can be) global across your site; whereas Panel layouts are per variant: node type, vocab, user role, etc, etc. For many sites you may end up with as many as 30 or more panel variants. This is cool and the main reason for using Panels (imo). But, if there are no Regions defined and Panels is used for your entire layout; this means you can not globally place a Block on your site (i.e site, not page). So, for example, if you want to add a User Login block; it is now necessary to add (and manage) that Content Pane on EVERY variant in your system. Sounds easy enough (and YES, very flexible); but significantly more work.

We recently launched www.spacenews.com which went a step closer to panels everywhere by replacing entire center area (left, right, content) with a single region which is then overridden (for all pages) by panels. This made it much easier to manage the complex mobile/responsive aspects of this site; but certainly brought with it many content placement (pane, block, etc) issues with it for the reason i mention above. And we still maintain regions for header and footer - even more painful content management had those been left up to Panels.

If i have any of this wrong (or right); please comment.

for further reading on the direction of managing content placement in Drupal: http://krisandju.e-webindustries.com/blog/drupal-8-blocks-layouts-everywhere

**Comment by uottawa-wcms** [comment]
I am curious if @sylus meant Blocks (core module) or blocks (Drupal concept). Blocks, as a module, is certainly a bit underwhelming in comparison to the alternatives. Creating custom blocks is an exercise in frustration for a multi-lingual site that's using the core module. 

We started using Bean to create custom blocks and found it went much smoother (they are similar to Boxes, but not as programmatic).

What we did for regions vs panels is limited Panels only to where we needed the ability to make a customized layout that involves components above and beyond a single piece of data and it's children (node, bean, snippet, term, user, etc). Panels has some overhead with it and in many cases we found it's simply not necessary to have that overhead.

We also did all the global elements of the site (header, main navigation, footer, contact, banner) through bean, generating a custom bean type for each that can be themed exactly how we want it and placed in a region. Different banners on different areas of the sites can be controlled via including / excluding the block on different pages (or through multi-sites). These are all consistent and standard for us, so we saw no reason to give anyone the ability to change them through Panels. However, since they're beans, we can swap them for other beans if we want, so we maintain a lot of flexibility in terms of the global layout, while being able to restrict it (by restricting access to the manage blocks feature) without also having to restrict access to Panels.

**Comment by liquidcms** [comment]
i think splitting into 2 concepts here: beans/blocks and panels/regions.

Haven't used Beans but it looks like it may be a fieldable block creation tool. Seems cool enough. "Creating custom blocks is an exercise in frustration for a multi-lingual site that's using the core module." - i didnt quite get that. Do you mean the core api for building custom blocks in code? this is pretty straightforward. Or perhaps you mean just the core block ui to build custom (html) blocks. Which is easy enough for i18n and i guess simple enough for html blocks. Perhaps i'll need to check out Beans to see where it falls in all of this.

As for regions/panels it sounds like you agree with what i was stating - "panels everywhere" in the purest form of this removes ALL but 1 region and makes placement of site wide blocks/beans/panes/etc impossible. So my initial question (although likely not that clear) is simply does Panopoly (and therefore the GoC distro) make content placement into regions impossible? Or possibly Panopoly has a way around this that Panels on its own doesn't support?

**Comment by uottawa-wcms** [comment]
That sounds like an @sylus question; we've been using a fairly heavily customized version of WET so what we've done may not apply to your project if you're using the distro out of the box. 

Creating custom blocks just using the core block module is kind of a pain precisely because it has to be done in code I feel. Our designers shouldn't need to work in PHP except where they have to and, given that Bean can avoid the need for raw code to define the type (except for theme template files, as most things need), it definitely seems like the superior choice (especially since they are also exportable into code if you need them to be).

**Comment by liquidcms** [comment]
@uottawa-wcms: does your "heavily customized version of WET" use Panopoly?

**Comment by sylus** [comment]
Not sure I am following. WET uses panels to replace the content region. All other regions are left intact. We debated going the panels everywhere approach but atm decided against it.

Basically the wrapper of the site is controlled through regions and the content region is controlled through panels.

We are doing basically the same thing as Ottawa U except with boxes instead of bean for the region workflow.

However after talking with Robert will likely swap out with Bean at some point.

**Comment by sylus** [comment]
Hmm actually reread the first comment where it said:

We recently launched www.spacenews.com which went a step closer to panels everywhere by replacing entire center area (left, right, content) with a single region which is then overridden (for all pages) by panels. This made it much easier to manage the complex mobile/responsive aspects of this site; but certainly brought with it many content placement (pane, block, etc) issues with it for the reason i mention above. And we still maintain regions for header and footer - even more painful content management had those been left up to Panels.

This is exactly what we are doing verbatim ^_^

**Comment by sylus** [comment]
So @uottawa-wcms are you stating you guys are not using a pure panels, views, ctools workflow for your content region? Not sure what you mean by panels causing overhead?

**Comment by liquidcms** [comment]
all sounds good. :) 

I was confused by "panopoly being panels everywhere" - which it sounds like it isn't (which is good) and by Will's comment at last WG that "Blocks were bad". Which i guess is more the idea of how blocks are created than how they are placed.

**Comment by sylus** [comment]
Exactly! apologies for the confusion. ^_^

**Comment by uottawa-wcms** [comment]
@sylus It's more editorial and workflow overhead (though Bryan says there is a performance impact as well). Setting up the panels layout for each page isn't really something we want to get into, since Panels is more complex than the node/bean management. Training our communications people on Panels seems unlikely. So we have two workflows:
1. Page is a simple content piece with no need for Panels features like Views integration or other widgets. We then simply define a content type and leverage a suggestion for node.tpl to format the page. Sometimes we're using Entity Reference to do simple relationships.
2. Page is a more complex piece with Views or multiple different pieces of content. We then make a layout if needed, a Panels page based on that layout, and then add in views and such to that page. We're not putting content into the panes though - we're using Views, some custom widgets (that don't have content, only configuration) and Content Snippets (which provides a fieldable entity which can be created and edited through Admin > Content, but which are exposed to Panels similar to how Views are exposed, so you can just drag them in).

As a result of this setup (which, I admit, is complex for developers especially since I get the joy of building it), our editorial users are left with a nice experience where they never have to directly touch Panels if they just want to change content or add simple types of content, which is a primary requirement for us. In the near future we want to add a gear menu to each piece of content (both within Panel pages and in simple node pages) that will give you access to the content edit form (as well as other things, like the Panels configuration) - this should make content editing even simpler and more consistent.
