### ISSUE TITLE
Align with OttawaU

### ISSUE THREAD

**Issue by sylus** [wet-boew/wet-boew-drupal#563]
Since we will be using the secsyn module created by OttawaU for deployment. It is important we try to align as much as possible to OttawaU.

First things first is to replace boxes with bean!

@uottawa-wcms

**Comment by sylus** [comment]
I like Beans architecture but currently it only allows for you to export the block type rather then the content. I know at first this was a design decision but I read in a few areas they have changed their mind. However these is currently no solution.

In order to replace boxes with bean I would need to have feature parity and this is one area bean is lacking.

@uottawa-wcms do you have suggestions for exporting bean data?

Currently I was looking at: http://drupal.org/node/1849668

**Comment by uottawa-wcms** [comment]
We haven't looked at it either. For syndication, we're using a generic method that is suitable for all fieldable entities. The patch looks like the right approach though - leveraging bean uuid to create an exportable.

His note about exporting any entities is very useful since we could leverage what I'm doing for syndication to implement that, but I don't have time to code it at the moment.

**Comment by sylus** [comment]
Yeah it is more so for a fresh install of the wetkit distro that we need some default content to show up.

**Comment by uottawa-wcms** [comment]
Agreed - definitely should patch it and support that patch.

Also, I just read a post about Boxes 2.0 which is apparently Beans + export/feature + other cool things. So it looks like Boxes 1.0 is deprecated anyways - Beans will ensure you're lined up for Boxes 2.0.

**Comment by sylus** [comment]
Yeah for sure, so I now have boxes working and also some code to provide default content on installation using entity translation so am fairly happy with that.

The last blocker is how to get beans to show up in panels. I was thinking just using: http://drupal.org/project/bean_panels

Should you agree with this can push the updated code and removal of boxes within a day!

**Comment by sylus** [comment]
Yeah this works great!!! :) Thanks for recommending this, definitely love the workflow and the power of bean!

Will commit this as soon as testing has been done and current boxes are themed into bean.

**Comment by uottawa-wcms** [comment]
Looks pretty good. Not sure I like the autocomplete for delta but I can't think of a better system at the moment (except leveraging however Views does it).

**Comment by sylus** [comment]
Yeah everything was going well till I tried adding bean to the install profile and it more then doubled the install time. I have checked this on a few other distros and same problem... Not so much a fan anymore lol.

For example: 

WET Install without Bean dependency: 410 secs
WET Install with Bean dependency: 1080 secs <--- this is crazy

This also has the unfortunate side effect of breaking Travis as it can sometimes hit the timeout limit.

**Comment by uottawa-wcms** [comment]
That's crazy ridiculous. I'm still working on our install profile but it seems odd that Beans would increase your install that much. It only takes about 10 seconds to drush enable for me through cygwin (and cygwin is VERY slow)

**Comment by sylus** [comment]
Yeah definitely odd at first I thought it was an interaction with ET but disabled that and still is crazy slow. I also used nodestream distro and it had the same result. There is definitely some problem with the Bean code going on.

**Comment by uottawa-wcms** [comment]
Have you tried a browser-based install? Does it hang on the bean side? My browser install take about 5-6 minutes but it doesn't seem to hang on bean.

**Comment by sylus** [comment]
Hmm no I exclusively use a drush si based install.

**Comment by StephenOTT** [comment]
Watching

**Comment by uottawa-wcms** [comment]
Definitely we should start thinking about install speed improvements in general. On Windows, it takes me nearly two hours to go from nothing to fully set up (this includes: cloning the initial repo for our install, running our drush make (15-20 minutes), running vagrant up (30-45 minutes), and running our install profile (45-60 minutes). I think most of it is the slowness caused by using Vagrant/Puppet mixed with the slowness of Windows CLI - the Mac environment is ready to go in under an hour (but I can't talk all the developers into using Mac/Linux systems).

**Comment by jmk1ng** [comment]
@sylus Is there an upgrade/migration path from boxes to bean? Trying to figure out what this means for existing sites that want to stay aligned with this project.

That might be a broader topic for a separate ticket though.,
