### ISSUE TITLE
Disable developer modules?

### ISSUE THREAD

**Issue by wcms-ottawa** [wet-boew/wet-boew-drupal#571]
Hello,

I noticed an issue when I tried disabling the developer modules where it basically broke my theme until I re-enabled the appropriate modules. It was a little surprising and I was able to recover okay however this is surely not desired.

Has anyone else experienced this? Please let me know if this is a known issue and if it has been addressed. I couldn't find it in any of the issues to date.

Thanks

**Comment by ssari** [comment]
It happened with me. Unfortunatelly, I don't have any idea why. I just reinstalled everything.

**Comment by wcms-ottawa** [comment]
Okay thanks for letting me know. I'll do a bit more testing to see if it is repeatable on my various builds.

**Comment by sylus** [comment]
Yeah the problem is when you click this option from admin menu it will disable all developer modules but if a module itself declares one of those developer modules as a dependency then that module will be disabled as well.

So say panopoly_core uses devel (as a dependency) which it doesn't but merely illustrative. Then when you would disable developer modules, panopoly_core would subsequently be disabled and all other modules relying on this.

@wcms-ottawa we could track down the culprit of this but I think views_ui would also be consider a developer module. I think this ultimately is a problem with admin_menu.

**Comment by wcms-ottawa** [comment]
Thanks sylus. I'll do some digging. Worse case I'll just remove the modules I don't need and disable the disable developer modules menu item :)
