### ISSUE TITLE
How to tell what version?

### ISSUE THREAD

**Issue by liquidcms** [wet-boew/wet-boew-drupal#657]
i just set up a copy of the distro and a few version control questions come to mind:
- what is latest version of the distro?
  -- i see a roadmap here: https://github.com/wet-boew/wet-boew/wiki/Roadmap (which lists milestones, which isn't really a roadmap; but is what i was looking for) - except this is for WET-BOEW not WET-BOEW-DRUPAL; couldn't find simliar page for Drupal variant
- is it possible to tell from the distro site itself?
  -- modules page lists WET modules as v1.0
- how to update to latest?
  -- i grabbed from git (which i see in my install is the master branch; and then ran required make script - which did go and grab latest of core and modules).
  -- i also ran the update script found here: https://github.com/wet-boew/wet-boew-drupal/wiki/Download%2C-Installation%2C-and-Update

so this would all seem to point to the idea that i have the latest and that the latest is 1.0 (well actually i guess would be 1.0+ as latest release is 1.0 but i am running off master branch)

my concerns with this stem from what it is have in my sample site:
- i was (possibly naively) under the impression that distro was using jqm; but this is not here
- i believe that (sadly) workbench was removed from the distro; yet it still exists in my copy
- and i was thinking there was some demo content included in the distro for things like the expand/collapse, complex tables, video player, etc that highlighted some of the WET integration. none of this is here either (but maybe i simply saw one of Will's demos but that was from content he added for his demo and it isn't part of the distro 

one other thing which i am not sure relates to this but i also ran the update process mentioned here: https://github.com/wet-boew/wet-boew-drupal/wiki/Download%2C-Installation%2C-and-Update which ran successfully except for the drush updatedb; which fails due to numerous issues with Variable module. but these are likely recent issues due to autoupdate script getting latest version of module which is listed incorrectly as having a version dependecy.

Error
    Unresolved dependency   Variable store (Version 7.x-2.x required)
Variable translation requires this module and version. Currently using Variable store version
Error
    Unresolved dependency   Variable realm (Version 7.x-2.x required)
Variable translation requires this module and version. Currently using Variable realm version
Error
    Unresolved dependency   Variable store (Version 7.x-2.x required)
WetKit MetaTags Dublin Core (HTML5) requires this module and version. Currently using Variable store version
Error
    Unresolved dependency   Variable realm (Version 7.x-2.x required)
WetKit MetaTags Dublin Core (HTML5) requires this module and version. Currently using Variable realm version
Error
    Unresolved dependency   Variable store (Version 7.x-2.x required)
WetKit WET-BOEW requires this module and version. Currently using Variable store version
Error
    Unresolved dependency   Variable realm (Version 7.x-2.x required)
WetKit WET-BOEW requires this module and version. Currently using Variable realm

**Comment by sylus** [comment]
1) Latest version of the distro: By the new year we are going to switch to strict tagging so versions will be much more apparent. Blockers on doing this are adding unit tests for every module and integrating with saucelabs.com (work is progressing on this.

2) The existing update in place commands do work.

3) WET uses JQMOBILE and is in the library for wet-boew this gets loaded automatically from WET

4) Workbench was officially added due to user feedback and decision was made to have it included by default till a better option is available (as of yet nothing better)

5) The advanced WET demo content can be added by enabling the WetKit Migration module and running the migration which will automatically import the WET HTML5 files into drupal. The migration is a bit slow but work is progressing on improving performance but the migration does work. (A grid system menu gets automatically imported.)

6) As for the notices this is because of variable translation:

I think this message only shows up when you use a git checkout, because then the respective module .info files will not contain a "version" string which is required for the dependency check. _We currently need to use the latest git repo_

**Comment by sylus** [comment]
I have 6 days off to work on this so will attempt to address this issues and / or document them better.

**Comment by liquidcms** [comment]
Well. If you have 6 days off. Go to Mexico or something. 

Peter Lindstrom,
LiquidCMS
