### ISSUE TITLE
Adding wetkit_adaptivetheme to an existing drupal install. Procedure?

### ISSUE THREAD

**Issue by candotri** [wet-boew/wet-boew-drupal#663]
Greetings,

I'm with the National Research Council of Canada. I'm an experienced Drupal developer (modules and themeing) but I have little experience with installation profiles or drush make. I do not use Windows, nor Aquia. I have module in the drupal.org sandbox waiting for review so I know a bit about compliance and such.

I want to use wetkit_adaptivetheme for a National Research Council Flagship project involving the genome sequencing of wheat.

Can you help me add the theme and modules to an existing site? I volunteer to document the procedure if that helps.

Here's what I did:

I got the git repository and symlinked wet-boew-drupal/themes/wetkit_adaptivetheme to sites/SITE/themes.

I also symlinked each of the modules in wet-boew-drupal/modules/custom/ to sites/ALL/modules and cleared cache. I don't remember _exactly_ what I did next but I would have looked for any missing dependencies and filled them.

My spidey sense tells me that I've done _exactly_ the wrong thing but I wasn't sure the best way to ensure that the custom modules were up to date without using symlinks. I bet that drush make is what I want but it wasn't clear how I can do that to a live drupal install that also contains several other sites.

Thank you for your work, I hope that with time I can contribute.

Chad Matsalla

**Comment by candotri** [comment]
OK, I abandoned that idea for now and went with the full profile install on a fresh drupal. I still think that if it is unreasonable to add wet-boew-drupal to an existing site I should write some documentation warning people. Perhaps it could say that "this is unsupported" or "it is too hard" if that's the case, or a page with some documentation if it is possible.

**Comment by candotri** [comment]
Anyone? Now that I have a functional website, do I always have to have a separate DRUPAL_ROOT for WET? I mean that's OK if that's the way it has to be but I'd sure like to get a recommendation from the developers as to why that's the case.

**Comment by kavinay** [comment]
I have the same wish, but I don't think you can easily separate the WET theme from the WET-Drupal package. We've made a similar request in the past and were informed that there are no plans to make a theme-only version of the project available.

In fact, I'm not really sure that they can. There is theming in the WetKit WET-BOEW module for example. Determining what parts of Wetkit are formatting output (theme system or module) is still tricky for me.

**Comment by candotri** [comment]
Yes, @kavinay, it's true that there are module dependencies. This is fine, though, because this is already a more involved install than is a typical theme.

Can someone tell me if wet-boew-drupal is being "distributed" as a complete install because drupal{6,7,8} do not have a mechanism to specify module dependencies? That's a bit bogus because you can look for required modules trivially in hook_preprocess_page and throw in error if they are absent. Or even put the dependencies in some sort of a readme. Sure this is involved - maybe a persistent variable indicating that the check was done would fix that at the expense of a query.

What I really want is some sort of document telling future users not to even try to make it work because of foo, bar, and baz.

Am I the only one out there who would be hosting more than one site in a drupal - one or more of which will use wetkit-boew-drupal?

**Comment by sylus** [comment]
I will try to add a more detailed response in the future but thought I would chime in and mention some of the reasons we can't simply extract out the wetkit-adaptivetheme and deliver it as theme only. :)

1) The WET JS Framework requires the libraries module: http://drupal.org/project/libraries. There are many reasons for this the primary one being that the libraries module allows us to tightly integrate with WET and easily support the 3 different themes it has (internet, intranet, and base). Thanks to the libraries integration you can easily change these settings in the WetKit WETBOEW menu. If this was a theme only integration you would not be able to easily do this and rely as WET as a separate library. Much of the beef of this code is here: https://github.com/wet-boew/wet-boew-drupal/blob/master/modules/custom/wetkit_wetboew/wetkit_wetboew.module#L329-474. Another key module that this theme relies on is menu_block which allows us to get more control on the drupal menu system to support the exact menu markup that WET needs to be responsive and also work in mobile mode. This can be found here: https://github.com/wet-boew/wet-boew-drupal/blob/master/themes/wetkit_adaptivetheme/templates/inc/template-menu-blocks.inc

2) Multilingual support: We have a mandate for bilingual menus, breadcrumbs, tokens, basically the whole front and backend interface so the theme has to take this into account. As such we use path_breadcrumbs, i18n, self created tokens, menu_block and i10n_client. Also our drush make process grabs the po files for all modules.

3) Many of the WET widgets including html5 video, tabbed interface etc need much more support then a theme can provide.

There are also a few other reasons that I would like to highlight and will try to take the time to do so. All that being said it might be possible to support a very stripped down theme that doesn't progressively rely on modules and will just disable functionality if those modules aren't present. Would certainly help in code quality and minimizing regressions. Will definitely take a look and am of course open to pull requests :)

**Comment by sylus** [comment]
There most certainly is a way to add this to an existing drupal install however! It might be a little tricky but if the module dependencies are met everything should work.

**Comment by mgifford** [comment]
Very interesting conversation.  This is something we've struggled with too.  Having contributed the previous Drupal CLF 2.0 theme we know that the Drupal WET Variant has taken on a much bigger challenge.  It's really quite amazing to see how far it has come in being able to package together so many best practices.  @sylus has really done an amazing job of taking us all beyond Core, pushing so many of us who knew Drupal to see how it can be used in a whole new way.  

Like all software, what is needed most to implement and sustain an initiative is critical mass.  In the CLF theme that we contributed there was little or no community around it to sustain it.  People used the theme, but rarely contributed anything back.  Unlike the CLF 2.0 framework though, WET is constantly being reviewed & updated.  This is essential as even if the usability were unchanging, accessibility requires regular modifications to keep up with changes in browsers & devices.  

I think that most of the work of producing a stand alone simple AdaptiveTheme sub-theme has already been done by @sylus.  Certainly AdpativeTheme and many of it's sub-themes don't have many if any required modules.  

The Drupal WET Variant will keep up with changes in WET, but I think we could really benefit by having a sub-group who can take what has been done and strip out as many module dependencies as possible.  Drupal 7 WET needs to be fully multi-lingual, but as Drupal becomes integrated in Intranet sites or regional sites such as I think @candotri is describing, I think that eventually we will see more unilingual implementations than bi or trilingual implementations.  

For us the challenge has been how to best fit the distro into our existing multi-site implementations.  We use drush extensively, but there are assumptions about the use of `drush make` that make it more difficult to fit into our existing infrastructure.  We're working on ways to get around that, but at this point all of our WET implementations have been for stand alone sites.  

It will be tricky though, both to remove the dependencies and also keep up with the modifications in the central Drupal Variant.  I guess the challenge is who wants to contribute the time & resources to build the theme and then maintain it?  

Under the hood Drupal is quite complex and because it is so flexible it can be very difficult to pull apart the related pieces.  @kavinay I don't know if your organization has resources to put into this, but adding to the documentation (even in the wiki here) is critical.  Explaining how it works is something that not everyone does well and that can be quite time consuming.  Does someone want to take responsibility for extending the documentation so that it is easier?

I know that both http://openconcept.ca or http://openplus.ca could implement this, but we are already contributing a lot to this project for free.  Is there anyone (possibly with year end money) who can pay for the initial work?  Is there anyone else who would step up to the plate to maintain it?

**Comment by kavinay** [comment]
@mgifford I'd love to add to the documentation, but unfortunately I still don't understand enough about the WET-variant myself to write it. :(

I suppose the obstacle I keep encountering is that I'm not aware of the design decisions taken by group that pioneered the WET-variant. As a result my assumptions on best practices are often not the same as the leads. This is by no means a criticism--I am certainly aware that I know far less about this than you guys.:) Rather, I'm just pointing out that some of the ideas that are _"baked-in"_ to the distribution are completely unknown to me and often undocumented (in terms of the overall project). As a result, an item such as integration/separation of theme is something that's sucked up a lot of time for me (and I'm assuming other developers who are not starting from scratch) to understand in respect to my production goals.

I would be happy to make a case to my organization to create a standalone theme. But I don't want to step on the toes of the project leads either. I've always been under the impression that they would like to keep the WET-Variant as a unified platform in order to facilitate growth through the app market. Ripping out the theme is indeed a bigger risk to building critical mass than banking on the maturation of the current all-or-nothing implementation.

**Comment by candotri** [comment]
I could spend the time to clarify and massage the documentation on this if one of the developers who knows can give me point-form (really brief is ok) lists of things to cover. It would be a good way for me to start contributing.

**Comment by sylus** [comment]
Closing old issues.
