### ISSUE TITLE
Migration best practices

### ISSUE THREAD

**Issue by ssari** [wet-boew/wet-boew-drupal#686]
With the constant changes in the distribution, @lpgascon and I are looking for solution to migrate the Wetkit application. 

Our attempt to migrate the full database, using phpAdmin or Backup-Migrate module, gives us Ajax error when customizing panelized pages.

Which tool are you using? And, what are the recommendations for a successful migration?

Thanks in advance.

**Comment by sylus** [comment]
The upgrade paths should have been pretty stable for the past few months or so. Are in place updates not working for you? I have been using in place updates at stats for the past 4 weeks with no hassle.

If the data you have is older then a few months. It is easy to use the migrate module to move content between drupal sites. The WetKit Migrate module shows example of how this works.

Apologies for the rapid changes in the codebase but we are finally ready for an RC1 release.

The delay was that I really wanted to get inline editing on the frontend working ala the Edit Module from Spark distro.

This will likely be released in RC2 so that tagging can be enforced and to maintain a more degree of professionalism in the builds rather then just using master branch ^_^
