### ISSUE TITLE
Question about the Mega Menu

### ISSUE THREAD

**Issue by elaberge74** [wet-boew/wet-boew-drupal#692]
I removed all item from my Mega Menu.  When I add new one and sub one, I would like that all items appear one under the other.. right now, it takes all space available at the right... 

See the attachment..

Thank you for you help !

![Megamenu](https://f.cloud.github.com/assets/3092924/112112/174ef3f6-6b10-11e2-849e-43ce6b60c835.png)

**Comment by sylus** [comment]
There is a trick to do this! :) Though arguably not very intuitive might have to write some documentation in the menu item form.

Due to the recursive nature of how the megamenu is built it is hard to support both these types of layout. Say you want to actually have it span to the right as you are using up to a depth of 3 instead of your current 2. The logic that implements this is at: https://github.com/wet-boew/wet-boew-drupal/blob/master/themes/wetkit_adaptivetheme/templates/inc/template-menu-blocks.inc#L110-185

A workaround that has been built is to pretend you are using up to a depth of 3 but exclusively remove the depth of 2 item.

So currently you have:

> Audiences
> 
> > Educators
> > Kids
> > Industry
> > Scientific Community

In order to get what you want you will have to use:

> Audiences
> 
> > Types (set path to `<noitem>`)
> > 
> > > Educators
> > > Kids
> > > Industry
> > > Scientific Community

This will then fire the custom logic here: https://github.com/wet-boew/wet-boew-drupal/blob/master/themes/wetkit_adaptivetheme/templates/inc/template-menu-blocks.inc#L159-161

**Comment by sylus** [comment]
Closing this for now but please reopen if more questions!
