### ISSUE TITLE
Problem with drush make

### ISSUE THREAD

**Issue by MichaelClift** [wet-boew/wet-boew-drupal#74]
When I try to build the project:

drush make --no-gitinfofile --working-copy https://github.com/wet-boew/wet-boew-drupal/raw/master/distro.make f:\wet

Output:
Unable to clone wetkit from                                              [error]

http://github.com/wet-boew/wet-boew-drupal.git.

No idea how to proceed.

**Comment by thriuin** [comment]
This command normally works for me - the only difference is that for the output directory I don't use the drive letter. Instead, I change to the parent directory and make in place with "wet" as the sub directory. (a long shot, I know...)

**Comment by MichaelClift** [comment]
No change.  Same error.

**Comment by sylus** [comment]
drush make uses wget and if that is not present curl. Can you verify that either of these commands work? Also can you do a basic git clone? You will need to have git installed on the command line.

**Comment by MichaelClift** [comment]
curl works and a basic git clone works

**Comment by sylus** [comment]
can you run the drush make with the --debug parameter and see if the output explains a bit more what is going on?

**Comment by sylus** [comment]
Also make sure you are using latest version of git with (git --version). I think version 1.7.1 has problems git cloning into a working copy. I use 1.7.11 but I think this was fixed in 1.7.7 onwards. You can test this theory by omitting the --working-copy in the drush make and seeing if the make builds.

**Comment by MichaelClift** [comment]
git version is 1.7.11 

Unable to clone wetkit from                                              [error]

http://github.com/wet-boew/wet-boew-drupal.git. [87.18 sec, 5.77 MB]
Command dispatch complete [87.18 sec, 5.61 MB]                          [notice]

Peak memory usage was 6.2 MB [87.18 sec, 5.61 MB]                       [memory]

Command dispatch complete [88.33 sec, 5.71 MB]                          [notice]

Peak memory usage was 6.48 MB [88.33 sec, 5.71 MB]                      [memory]

**Comment by sylus** [comment]
And I assume your drush version is 5.4 or higher as well?

Another shot in the dark is your cache is causing problems. Can you rm -rf the drush cache folder usually in ~/.drush/cache (home folder)

**Comment by sboots** [comment]
I had a similar error on Windows, and the fix was to write the destination folder in Unix format -- eg. in your case, instead of f:\wet, it would be /f/wet

Assuming that you're using msys.bat, and then typing bash, and then using the command above. There might definitely be other ways of doing the same thing.

My run-through of the installation on Windows is here:
https://github.com/wet-boew/wet-boew-drupal/issues/22#issuecomment-6427278

All the best!

**Comment by sylus** [comment]
@sboots thanks for the help!

I should have asked @MichaelClift are you running these commands through msysgit or some other cli? 

Hopefully what @sboots suggested will be of some help. Otherwise I will look more into this and improve the instructions.

**Comment by sboots** [comment]
No problem!  Running through msysgit.  Inside the msysgit folder, there's the msys.bat file, which opens up a Git-flavoured (is that the word?) command prompt.  Then, type bash, then, type the commands as listed (adjusting windows-style folder paths to unix-style ones.)

**Comment by sboots** [comment]
Also, one other possibility: in one case, we were installing onto a computer within our department's firewall, which has been set to block all tar.gz files.

The easiest test is to try manually downloading eg. http://ftp.drupal.org/files/projects/drupal-7.14.tar.gz on the machine in question.  If that doesn't work, then you can expect the drush commands to fail with all sorts of interesting errors (when they get HTML firewall block messages, instead of tar.gz install files).  That was a puzzle...

**Comment by sylus** [comment]
Yeah another reason for me to get the built out version up on another repo. Which will happen before codefest tomorrow ^_^

**Comment by sboots** [comment]
Aha, all good!  :D  Seriously, epic work on this.  I tip my hat - never seen Drupal at this level before.

See you at the codefest tomorrow!  Sending good vibes for everything on the go before then.

**Comment by MichaelClift** [comment]
blech - i'm so confused and tired.... i've probably screwed everything up - shelving it until tomorrow

**Comment by thriuin** [comment]
Since Michael was able to get a basic clone, then whatever firewall issues, if any, he may have had must be resolved. He also tried to use a path that didn't have a windows drive letter, as per my first suggestion, but that didn't seem to help either.

One thing I was curious about, is that the error Michael copied includes an HTTP address "http://github.com/wet-boew/wet-boew-drupal.git." and not HTTPS. Relevant or a red herring? Based on the transcript, it seems takes a while to crap out so there's probably some time-out happening.

**Comment by sboots** [comment]
Hm, interesting. : / If we figure out more reasons why this sometimes fails we should definitely write them down.

No worries Michael!  If you're at the codefest tomorrow (maybe with a dev laptop?) we can definitely poke at installing it there.  All the best!

**Comment by MichaelClift** [comment]
I'm not sure if its a red herring, but the line in question comes from the distro.make file.

**Comment by sylus** [comment]
I don't think it makes a difference but for consistency it really should be https so fixed that.

**Comment by sboots** [comment]
Morning folks!
Just tried a re-install this morning, and it came up:
`The 'core' attribute is required                                     [error]
You need to specify an API version of two in your makefile:          [warning]
api = 2`

No stress though; we can get it rolling at the codefest this afternoon.

**Comment by sboots** [comment]
Never mind! Back in business. Sorry about that; must have been a temporary quirk. Things are rocking.

**Comment by sboots** [comment]
...and, jinxed myself again. : P
`WD php: Exception: Sorry, the profile you have chosen cannot be      [error]
loaded. in install_load_profile() (line 1314 of
/Library/WebServer/Documents/w7/includes/install.core.inc).``

**Comment by MichaelClift** [comment]
sboots approach worked for me...

**Comment by sylus** [comment]
Hey @MichaelClift could you clarify what your exact problem was? Is this something other people would run into? I'd like to minimize the hassle people have in using drush make so if you could point to some areas the documentation is lacking that would be greatly helpful. 

Based on that feedback I will improve the write up :) Either way great you got it going!

**Comment by MichaelClift** [comment]
I opened msysgit.bat, ran 'bash' and it worked with the following caveat....
I followed: 
 https://github.com/wet-boew/wet-boew-drupal/issues/22#issuecomment-6427278

except the drush.bat wasn't on my path so instead of:
drush make --no-gitinfofile --working-copy https://github.com/wet-boew/wet-boew-drupal/raw/master/distro.make /f/wet

i included the full path:
/c/ProgramData/drush/drush make --no-gitinfofile --working-copy https://github.com/wet-boew/wet-boew-drupal/raw/master/distro.make /f/wet

Essentially, my problem originated from using the "Drush Command Prompt" which is not the equivalent of bash even though I could call both git commands and drush commands from it.

**Comment by sylus** [comment]
Awesome I will try to reflect this in the readme :) I really appreciate your help and patience in setting this up. Definitely have to make the docs more concise.

**Comment by RobJohnston** [comment]
Interesting... I have a different process that I'll add for comparison.

I had to be an admin to get the Drush Windows Installer to run, but for my normal everyday work I don't use the admin account, so I start by opening a command prompt and typing <code>"C:\Program Files (x86)\Drush\DrushEnv.bat" </code> (with the quotes).  I then see a message that says “Command Prompt shell optimized for Drush”.

Once opened, I type the following to enable Git: <code>C:\msysgit\msys.bat</code>.  I then see a message that says "Welcome to msysGit".

Now I'm in a position to type <code><pre>drush make --no-gitinfofile --working-copy https://github.com/wet-boew/wet-boew-drupal/raw/master/distro.make C:/Users/r_johnston/Projects/drupal_wet</pre></code> and the direction of those slashes on my local drive is important!

Also,I do have to remove the contents of the .drush/cache/download directory on occasion.
