### ISSUE TITLE
PHP Fatal Error on drush updatedb

### ISSUE THREAD

**Issue by TheDuke13** [wet-boew/wet-boew-drupal#750]
Hi, we were trying to update a sandbox we've installed and ran into a problem after the git pull and make, when we executed the drush updatedb
here's the message we get:
PHP Fatal error:  Cannot redeclare adaptivetheme_drush_command() (previously declared in /var/www/html/profiles/wetkit/themes/adaptivetheme/at_core/adaptivetheme.drush.inc:13) in /var/www/html/sites/all/themes/adaptivetheme/at_core/adaptivetheme.drush.inc on line 35
Drush command terminated abnormally due to an unrecoverable error.                                                                                [error]
Error: Cannot redeclare adaptivetheme_drush_command() (previously declared in
/var/www/html/profiles/wetkit/themes/adaptivetheme/at_core/adaptivetheme.drush.inc:13) in
/var/www/html/sites/all/themes/adaptivetheme/at_core/adaptivetheme.drush.inc, line 35

here is some info on what we're running this on:
Fedora Core 17,  kernel 3.7.3-101.fc17.i686.PAE, drush 5.8, drupal 7.19, git rev-parse HEAD: 058360a8d26baa5793cee69e61d5da3f84928aeb

If you could give me some insight on why we're encountering this issue it would be great.

Thanks!

Carl

**Comment by antatar** [comment]
Would be interested as well - I've run into this problem myself during the update. Removing the declarations mentioned results in more fatal errors. Tried removing the entire directory - the DB Update worked, but the site no longer had the template installed. 
thanks.

**Comment by sylus** [comment]
Hey quick clarification? Was this an update from RC1 to one of the hotfixes or was an earlier sandbox before we were using RC1?

It looks like you have two versions of adaptivetheme which leads me to think you are trying to update from before RC1. We are working on this process as RC1 now uses the drupal standard way of doing builds so modules, themes that are part of the distro now belong in /profiles/wetkit instead of /sites/all/libraries.

This is likely why it looks like you have both?

So clarification:

Before RC1 - RC1 this will require some additional work and we are in process of upgrading Stats to RC1 and will be documenting the work
RC1 onwards supports an upgrade path and each release will specify the steps

**Comment by TheDuke13** [comment]
Earlier sandbox (built around Feb 8th)

**Comment by sylus** [comment]
K luckily there should be an upgrade process for builds around February pre-rc1 as StatsCan is in the same point. When the process is finalized I will post back here.

**Comment by TheDuke13** [comment]
Alright! Thanks for the update, keep me posted if you make process on an update procedure or script.

We've started work on this SandBox for our internet project but will have a separate one created from the new RC1 for an Intranet Segment.

Thanks!
