### ISSUE TITLE
Oracle and Drupal advice

### ISSUE THREAD

**Issue by MaddyDaigle** [wet-boew/wet-boew-drupal#763]
Hello everyone,

I was wondering if I could get some input on implementing Drupal with an Oracle database.  At the Drupal Camp in Ottawa I was talking to a few people who had tried this and had a lot of problems with it.  We were planning on using Drupal with Oracle for our Infoweb at the RCMP. After the conversations I had that day, I'd like to get some more information as to why this would be such a difficult process.  What would we actually have to do to get this working, what are the incompatibilities, etc.. Could anyone point me in the right direction to get some good information on this? We haven't starting looking into implementation yet, so I'd like to get a heads up. Also, I was wondering who has actually tried getting Drupal working with Oracle.  I remember talking to someone at Drupal camp but forgot to get their name. >_<

Thanks so much!

**Comment by joel-osc** [comment]
You can talk to the folks at Transport Canada, Matthew Winstone was the developer there from ColdFront labs. From my conversation with him it has been absolute hell getting the site working with Oracle. There are a few reasons for this, the biggest one being is that this is OpenSource software - 99% of the development community uses an OpenSource stack - meaning LAMP. Once you stray from that you open yourself up to a lot of issues that no-one else will see and then you get stuck figuring them out which negates one of the biggest advantages of Drupal which is the community.

When it comes to choosing a web server (IIS/Apache) straying from the pack may not be as problematic because there are standards to which both must comply. However, there is little standard implementation for SQL and database interaction between the different database vendors so the database abstraction layer must be very aware of the database being used. And, every module must use the database abstraction layer instead of doing SQL directly - which is not necessarily the case in Drupal so you will end up fixing a lot of modules to use the database abstraction layer correctly.

I know it may be tricky to convince IT that Oracle is not the right choice here, but the difference is going to be a project which takes you 10x longer and at 10x the cost.

**Comment by MaddyDaigle** [comment]
Thank you so much for your help!  I'll definitely try and get in contact with Transport. :)

**Comment by RobJohnston** [comment]
With my experience running Drupal on MS SQL Server, I'd agree with everything that @joel-osc said, except it wasn't 10x longer.  I had to dig around, but most everything has patches waiting to be committed or discussions about how to solve problems.  However there are some landmines still sitting out there, waiting to be stepped upon.

**Comment by MaddyDaigle** [comment]
I'm assuming your experience is with starting fresh with an entirely new Drupal distribution, right?  Trying to make wet-drupal compatible with Oracle would probably take considerable time and effort.

**Comment by LeeHunter** [comment]
Any IT department that standardizes on a certain corporate database, whether DB2 or Oracle or something else, _always_ has a number of other databases lurking on their corporate networks. Those other databases are allowed because they come packaged as the data management part of various off-the-shelf software products. In fact, if IT got total religion about only allowing one database, the business would probably just grind to a halt, because there are lots of important applications that don't run on Oracle. 

So the question in my mind is whether Drupal is really much different than any other off-the-shelf product in that little to no in-house coding is done to the MySQL database, it generally doesn't require any special DBA effort and it can easily be made interoperable with other systems.

**Comment by xmacinfo** [comment]
Please contact the Drupal Oracle driver module maintainer to see if your requirements are met by his Oracle module.

https://drupal.org/project/oracle

**Comment by MaddyDaigle** [comment]
I've looked into that module before and have already messaged the maintainer.. haven't received a response yet.  I was just hoping to get input from anyone with prior experience with Oracle and Drupal as well.  I was very much advised against using it with Oracle at Drupal camp and just wanted to get some more opinions on this.

Thanks everyone for your input. :)

**Comment by xmacinfo** [comment]
I would then suggest asking Damien (https://drupal.org/user/22211) his point of view on current stage of Oracle solutions for Drupal 7. Damien did work on database driver modules for couchdb, mongodb and MS SQL Server. So he might already have a pretty good idea.

He might also be able to refer you to a developer who would be able to create the full driver as paid work.

Another one you might chat with is CHX (https://drupal.org/chx). He should be able to tell you if creating the driver for Oracle with your full requirements is possible.

**Comment by joel-osc** [comment]
I don't really know if the quality of the driver is that relevant...the key issues are the reliance on all the other module developers to code using the correct database abstraction layer and lack of code coverage on the Oracle platform.

If you count (grep) the number of calls to 'db_query' on a typical site you will find hundreds of hits. There are 600+ on the site I tested which was simply Drupal Wet + OG. These would all need to be looked at and in all likelihood patched to use db_select instead, and then as modules are added / upgraded this would need to become a continuous process until the module maintainer adds your patch(es) to the build. This would create a lot of extra work which would otherwise be unnecessary if you had chosen the standard LAMP stack.

Also when assessing the viability of the Oracle module you can look on Durpal.org and see that only 115 sites currently report using the Oracle module compared to a module like Views which reports 611018 sites. This means that this module is not really being used and the community would not be providing you any test coverage (and subsequent fixes) for any modules which interact with the database - which is almost all of them.

I would be careful using the quality of the driver as a factor in this decision because even though there are only 22 open defects against the Oracle module the defects that this type of module would uncover would mostly be raised against other modules.

**Comment by ssari** [comment]
Hi Maddy.
It was May that gave you some suggestions http://coldfrontlabs.ca/about in the code sprint session.

**Comment by openplus** [comment]
I completely agree with Joel on this... I know this was also a key conversation at StatsCan. (Which had pressure to use Oracle, but after a full evaluation, opted not to... for very valid reasons).
You can actually get enterprise support for MySQL from Oracle now (ironically)
You'll get better performance using NGINX and a good Varnish config anyway.
Also, you can us webservices to get data in/out if you have equity in Oracle... but the case to run it on Oracle just don't hold up (unless you run the most vanilla Drupal deployment ever... which is pretty much impossible, - hence the DrupalWxT distro has a hundred+ modules and patches)

**Comment by sylus** [comment]
Cleaning up some old issues. :) and this looks pretty answered, no way the two will work together!
