### ISSUE TITLE
Default Drupal Logo not functional

### ISSUE THREAD

**Issue by d-shields** [wet-boew/wet-boew-drupal#802]
Hey,
Just realizing that the site logo is built in a somewhat unconventional way and wondering what the thinking was behind that.
Typically, when you want to add a site logo, that can be done through the UI in the theme settings, but this feature is not functional with the WET page--panels--wet.tpl.php template file.
For my own purposes, I've just coded it back in, but I'm wondering why this core feature of drupal was disabled in WET.

Thanks!

**Comment by sylus** [comment]
Hmm could have been I knew the logo that was needed (Canadian Leaf) so forced it but probably not the best way.

Can you do a pull request so I can see the code you would wish to add?

**Comment by d-shields** [comment]
done.
thanks @sylus 
I guess this should be done for all 4 of the theme options (not sure about this for the Internet theme, depending on context) and for both the page--base.tpl.php as well as the page--panels--base.tpl.php.
If you're happy with my solution, let me know and I'll fix up those files in the same way.

**Comment by sylus** [comment]
I am going to mark this as won't fix because often times WET uses a svg which has a special type of markup that isn't supported by the interface.

**Comment by mgifford** [comment]
The real question here is, is this going to be just a Government of Canada distribution or are folks with different brand requirements going to be encouraged to participate as well.  

If WET wants to be broad enough that other organizations can participate, then this is an issue that should be re-opened.  

Ultimately, it's a matter of a few lines of code in the template file to check to see if a logo has been updated.

**Comment by sylus** [comment]
I don't think this is an issue with brand requirements. It is more an issue of using an svg as the logo which is becoming an increasingly common best practice.

How is this specific to Government of Canada?

**Comment by mgifford** [comment]
In every Drupal theme I've ever tried, you can upload a logo and it will appear in the theme.  

As it is, if anyone wants to do anything other than a GoC site one of the first things they will try is to change the logo.  The Drupal way is to go into the settings page for the theme, uncheck "Use the default logo" and upload their organizations logo.  

This is still an option in WET on the admin side but it doesn't come through to the theme.  

It's quite probable that many GoC sites won't be changing their logos (except perhaps on the Intranet) and so this isn't an issue that affects them.  

For most other agencies though it will be one of the first places they will start.  Particularly if they are familiar with Drupal but not with the WETKit distribution. 

As far as using SVG, why not work to fix that problem in D8 & have it backported to D7 rather than just break functionality in Drupal because someone might want to use SVG?

I think this is the issue - https://drupal.org/node/1507896

**Comment by sylus** [comment]
I have added support for SVG and the logo + site name toggle.

**Comment by mgifford** [comment]
Thanks!
