### ISSUE TITLE
WetKit Menu Module

### ISSUE THREAD

**Issue by sylus** [wet-boew/wet-boew-drupal#818]
A nifty and powerful new feature will be added in RC2 the addition of the wetkit_menu module.

This module draws code and inspiration from: 

http://drupal.org/project/menu_minipanels

So we can now get menus like this:

![Mega Menu](https://f.cloud.github.com/assets/984304/336836/c762c2a2-9cb3-11e2-9716-de356967adee.png)

Leveraging familiar tools like this:

![Panels Screen](https://f.cloud.github.com/assets/984304/336844/00b069d8-9cb4-11e2-9728-b3e2d80bf6ea.png)

Added to menu items through the menu system:

![Menu System](https://f.cloud.github.com/assets/984304/336856/91fca622-9cb4-11e2-858b-f55ca785bb16.png)

Menu system will now be configurable through panels and all the functionality that that provides. (visibiity rules etc...)

Additionally the logic of the mega menus has been simplified and the menu block on the side based on the megamenu now renders perfectly:

![Sidebar](https://f.cloud.github.com/assets/984304/336849/452c5cac-9cb4-11e2-86db-bcb157eba702.png)

So need to document how the new system works. Once an initial learning curve is gotten past the module becomes very easy to use.

Credit goes to @joel-osc for the awesome idea!

**Comment by sylus** [comment]
@mgifford @LeeHunter @StephenOTT @joel-osc @joejoseph00

**Comment by mgifford** [comment]
That's really quite neat. So you could easily bring in search blocks or image galleries in there too.

**Comment by d-shields** [comment]
We used Menu minipanels on http://cpac.ca for the Shows dropdown menu - I liked the concept a lot - gives extreme flexibility for quick, simple navigation with visuals

**Comment by mgifford** [comment]
Is there a way to contribute the changes back to Menu minipanels? Couldn't this just be something that's themable?  

Being able to do this is definitely cool.  However, what of this new code do you really want to be maintaining?  Is there a way to just leverage this module (or at least contribute a big patch back to this module)?

**Comment by sylus** [comment]
No unfortunately menu minipanels relies heavily on qtip and we rely on wet as the js layer. Additionally there were too many customizations done across the board to merit a patch.

The code itself is pretty light weight mostly revolving around hook implementations :)

**Comment by mgifford** [comment]
Ok, so because the module is pretty light code wise & uses a different jQuery plugin that would have to be downloaded separately it made sense to fork the project (that's ok) and not leverage the herd of 1887 known users so that a page could be loaded faster with less JS just leveraging tools available in WET.

I haven't looked at this, but just want to make these tradeoff's explicit.  If there's a reason to move away from stable module on Drupal.org to one that's built for WET then it should be documented.  There are always costs associated with maintaining software, so the more software that is being maintained elsewhere the more eyes you have on ensuring that the code base continues to work.

**Comment by StephenOTT** [comment]
@StephenOTT

**Comment by sylus** [comment]
Module is in and working well and has been tested with Health Canada to great effect. 4 contextual mega menus + Top Nav.
