### ISSUE TITLE
Can't delete content types

### ISSUE THREAD

**Issue by MikeDucharme** [wet-boew/wet-boew-drupal#845]
I tried deleting the Basic page (Deprecated) and the Documentation types but the content types remain intact. There are no errors or warnings and the message says that they were successfully deleted.

```
/admin/structure/types/manage/wetkit_page_other/delete
```

![wet-delete-content-type-a](https://f.cloud.github.com/assets/82974/363527/5eb9a45c-a206-11e2-818c-b9bcde5466bd.gif)

![wet-delete-content-type-b](https://f.cloud.github.com/assets/82974/363531/6cff3680-a206-11e2-802b-8876a857c078.gif)

Log Messages - i18n_string seems to automatically regenerate strings on the deleted content type, which is a clue:

```
i18n_string 2013-04-10  Created string node:type:wetkit_page_other...   openconcept 
i18n_string 2013-04-10  Created string node:type:wetkit_page_other...   openconcept 
i18n_string 2013-04-10  Created string node:type:wetkit_page_other:title... openconcept 
i18n_string 2013-04-10  Created string node:type:wetkit_page_other:title... openconcept 
i18n_string 2013-04-10  Created string node:type:wetkit_page_other:name for...  openconcept 
i18n_string 2013-04-10  Created string node:type:wetkit_page_other:name for...  openconcept 
node    2013-04-10  Deleted content type Basic Page (Deprecated).   openconcept 
i18n_string 2013-04-10  Deleted string node:type:wetkit_page_other:title... openconcept 
i18n_string 2013-04-10  Deleted string node:type:wetkit_page_other:name for...  openconcept 
i18n_string 2013-04-10  Deleted string node:type:wetkit_page_other...   openconcept 
i18n_string 2013-04-10  Deleted string field:field_featured_image:wetkit_page...    openconcept 
i18n_string 2013-04-10  Deleted string field:body:wetkit_page_other:label for...    openconcept
```

Branch: feature-wet-v3.1
Firefox 19, OSX 10.8.3

**Comment by sylus** [comment]
This are features controlled and created content types. They can't be deleted.

Although I will probably be removing the basic page (deprecated) shortly from the feature.

Alas not much I can do about the other content type though.

**Comment by mgifford** [comment]
Why can't they be deleted? What logic has been hard coded into the distro such that we can't clean up and focus the code based on our needs?

If WET breaks when a content type is deleted, then WET is broken if you're still allowed to press the delete button.  

When there are basic Drupal things that you can do, but not in WET, there needs to be inline documentation to explain why this can't be deleted and code to at least hide the delete button from the user.

**Comment by joel-osc** [comment]
This has nothing to do with WET, it has to do with features. If something is added via a feature then it cannot be deleted via the UI. As Will says, the Basic Page (deprecated) will be removed from the feature shortly, but otherwise it would be good to have a single content in the distro to begin with. Perhaps we leave this open to track the deletion of Basic Page (Deprecated) or dup it to an existing case on that if one exists.

**Comment by sylus** [comment]
Yeah exactly what @joel-osc said. Also a quick clarification there is no delete button for the removal of these features. That is what @MikeDucharme was asking why it is **NOT** present.

Nothing in this issue has to do with WET. WET really doesn't go against any Drupal practices.

**Comment by xmacinfo** [comment]
Although content types can be added to features, usually it’s best to not to do that.

It is preferable to create the content type in a module and use the .install file to create the complete content type and use a hook_uninstall to delete cleanly the content type, along all the fields used by that content type.

**Comment by MikeDucharme** [comment]
Actually, there is a Delete button, which is how I was able to delete them in the first place. They are available in the Administration menu for every content type:

![wet-delete-content-type-c](https://f.cloud.github.com/assets/82974/364062/1a44cbb2-a215-11e2-9988-d6b4588ef965.gif)
:

**Comment by sylus** [comment]
@xmacinfo on what basis are you saying content types shouldn't be added using features? Every other distribution does this and it is standard practice. I dislike adding content types through the standard means because you lose the ability to see if the content type has been overridden and also the ability to revert should changes have occurred on the content type. Additionally you can see a diff between what was changed in the features interface. This is a very powerful feature and one I am not inclined to lose without clear benefits on the other side. Also it doesn't hurt that the content type is cleanly exported passing PHP Code Sniffer and prevents you from doing the copying etc yourself which can result in breaking the strict indentation rules Drupal wants you to adhere to.

@MikeDucharme I see what you mean this is admin_menu being a bit sneaky and I will find a way to remove that delete option. I was referring to the actual content type interface where delete was not present.

**Comment by sylus** [comment]
This issue might address concerns with using Features + Field Instances: http://drupal.org/node/1064472

Issue Summary

Fields exports in features combine in a single export what are really distinct forms of data: the base field definition and the field instance information. Therefore, field definitions are duplicated in multiple places, one per field instance export. This duplication produces several difficulties including:

To make a change to the field definition, it is necessary to update multiple field exports rather than just one.

Proposed resolution

The current patch separates field exports into two parts: field_base and field_instance. New export will contain these new component types, but existing legacy features are still supported.

**Comment by xmacinfo** [comment]
@sylus Features supports content types and this fine for most situation and distributions.

However, at TVA, in Montréal, updating a Feature, that included a content type, sometimes resulted in data loss. A decision was made to create the content types in a module directly without using feature.

Feature is kept for everything else, but not for the content type over there.

Issue at http://drupal.org/node/1064472 looks nice. I have not tested this yet.

**Comment by sylus** [comment]
We are now using Features Beta 2 which uses: http://drupal.org/node/1064472

This means the field instance is separated from the field base definition which is often in a different or distribution_core module.

This solves many of the issues aforementioned above.

I have also removed the deprecated menu.

Unfortunately for the delete showing up in Admin Menu I think this is an upstream issue to that module, as on the field screen itself the delete does not appear which is the correct behavior.

**Comment by sylus** [comment]
No longer see this error so must have been fixed :)
