### ISSUE TITLE
WET Theme missing from feature branch on most recent build

### ISSUE THREAD

**Issue by d-shields** [wet-boew/wet-boew-drupal#860]
Hey @sylus,

we're having a bit of trouble keeping up to date with the code changes while developing on the feature branch.

The Wet Theme folder is missing in this Feature branch change:
profiles/wetkit/libraries/wet-boew/dist/theme-wet-boew/

We're getting file not found errors while the "Wet Theme" is set:
/admin/panopoly/wetkit_settings/wetkit_wetboew

**Comment by sylus** [comment]
In build-wetkit.make before your build for that branch did you remember to change master to latest revision, otherwise your still on master branch which is v3.0.

6b5ad25042c752d52b6f7a91559a10a782908775

So build-wetkit.make before build would look like:

```
api = 2
core = 7.x

projects[drupal][version] = 7.22
includes[] = drupal-org-core.make

; Drupal.org packaging standards
projects[wetkit][type] = profile
projects[wetkit][download][type] = git
projects[wetkit][download][url] = https://github.com/wet-boew/wet-boew-drupal.git
projects[wetkit][download][revision] = 6b5ad25042c752d52b6f7a91559a10a782908775
```

Either tonight or tomorrow I will have 3.1 on Drupal.org

**Comment by sylus** [comment]
Just did a build myself and works great, According to Travis built + installed in 7 mins 34 seconds :)

**Comment by sylus** [comment]
Ran a few manual and automated builds so think this was just a case of not adding the commit sha. Look for this to be up on Drupal tomorrow!
