### ISSUE TITLE
Problems with step #2 under Build and launch the WetKit Drupal Distribution

### ISSUE THREAD

**Issue by WayneWhitten** [wet-boew/wet-boew-drupal#921]
Drush isn't working for me on step #2.  I'm not sure I have the command line correct.  Is there another way, perhaps a manual one that I can follow?  I've already extracted the zip into /drupal_wet so I don't believe a "make" is needed.  Please correct and advise, and if more info is needed.

I gave up on the acquia desktop installation and working from scratch with WAMP and then Drupal.  That installation works, so with a known good starting point I'd like to add WET and would appreciate extra help.

**Comment by joejoseph00** [comment]
So you've got Windows (XP?, 7?, 2008r2?)  and php has been installed?  Step #2 is install Drush, 

Install Drush 5.8 or higher (inlcudes Drush Make):

```
b) Windows: http://drush.ws/drush_windows_installer
```

I recommend version 5.8

http://drush.ws/sites/default/files/attachments/Drush-5.8-2012-12-10-Installer-v1.0.20.msi

The system requirements are here.

https://github.com/wet-boew/wet-boew-drupal/wiki/System-Requirements

What version of PHP do you have?  assuming WAMP, what version of WAMP?  what version of apache, what version of MySQL, what version of PHP are you running?

Step 3 you'll need to get Git 1.7.10 or higher 

this is a start

**Comment by alar2** [comment]
Me too!
On Windows 2008 Server R2
acquia desktop installation --> success
Virtual Host set up for drupal_wet (same port as acquia for now...)

Apache Web Server Version 2.2.22
PHP 5.3.18 (cli) (built: Oct 17 2012 19:55:13)
mysql  Ver 14.14 Distrib 5.1.66, for Win32 (ia32)
drush version 5.8  (from Drush-5.8-2012-12-10-Installer-v1.0.20.msi)
git version 1.8.3-rc3 (msysGit)

+++++++++++++++++++++++++++++++++++++++
$ git clone https://github.com/wet-boew/wet-boew-drupal.git profiles/wetkit;
Cloning into 'profiles/wetkit'...
remote: Counting objects: 13546, done.
remote: Compressing objects: 100% (4641/4641), done.
rRemote: Total 13546 (delta 8252), reused 13222 (delta 8035)eceiving objects: 10
Receiving objects: 100% (13546/13546), 14.22 MiB | 1.26 MiB/s, done.

Resolving deltas: 100% (8252/8252), done.
Checking out files: 100% (565/565), done.

++++++++++++++++++++++++++++++++++++++++
E:\htdocs\sites\drupal_wet>drush make --prepare-install --no-gitinfofile --working-copy E:\temp\wet-boew-drupal\build-wetkit.make --yes -v
.
.
.
Project drupal contains:                                               [success]
- 3 profiles: testing, standard, minimal
- 4 themes: stark, seven, garland, bartik
- 47 modules: drupal_system_listing_incompatible_test,
  drupal_system_listing_compatible_test, user, update, trigger,
  translation, tracker, toolbar, taxonomy, system, syslog, statistics,
  simpletest, shortcut, search, rdf, profile, poll, php, path, overlay,
  openid, node, menu, locale, image, help, forum, filter, file,
  field_ui, text, options, number, list, field_sql_storage, field,
  dblog, dashboard, contextual, contact, comment, color, book, blog,
  block, aggregator

Command dispatch complete                                               [notice]
drupal-7.22 downloaded.                                                     [ok]
Executing: which wget
Executing: curl --fail -s -L --connect-timeout 30 -o "C:\Users\lob-sa-username\AppData\Local\Temp\2\dowE59E.tmp" http://drupal.org/files/issues/install-redirect-on-empty-database-728702-36.patch
Unable to download                                                       [error]
http://drupal.org/files/issues/install-redirect-on-empty-database-728702-36.patch.
php.exe "C:\ProgramData\Drush\drush.php" --php=php.exe               [notice]
--backend=2  make-process
"C:\Users\LO759D~1\AppData\Local\Temp\2/make_tmp_1370647075_51b26a23103d3"
2>&1
Loading release_info engine.                                            [notice]
Unable to clone wetkit from                                              [error]
https://github.com/wet-boew/wet-boew-drupal.git.
Command dispatch complete                                               [notice]
Command dispatch complete                                               [notice]

---

I was able to get farther than this on a xampp install that had php 5.4 , but I blew all that away for a tried and true acquia environment.
:(

I've installed the Drupal WetKit on Linux and my Windows machine at work. Alas, I am stumped!!!
Ideas?????

**Comment by alar2** [comment]
I think this is the problem, but not sure why it's happening now! 
From command line: wget https://github.com/wet-boew/wet-boew-drupal\build-wetkit.make

E:\htdocs\sites\drupal_wet>wget https://github.com/wet-boew/wet-boew-drupal\build-wetkit.make
SYSTEM_WGETRC = c:/progra~1/wget/etc/wgetrc
syswgetrc = C:\Program Files (x86)\Drush\GnuWin32/etc/wgetrc
--2013-06-07 21:22:45--  https://github.com/wet-boew/wet-boew-drupal%5Cbuild-wetkit.make
Resolving github.com... 204.232.175.90
Connecting to github.com|204.232.175.90|:443... connected.
ERROR: cannot verify github.com's certificate, issued by `/C=US/O=DigiCert Inc/O
U=www.digicert.com/CN=DigiCert High Assurance EV CA-1':
  Unable to locally verify the issuer's authority.
To connect to github.com insecurely, use`--no-check-certificate'.
Unable to establish SSL connection.

Maybe on Monday I can add --no-check-certificate to my local temp copy of build-wetkit.make. Hold on. How? 

First google hit is:

2.8 HTTPS (SSL/TLS) Options

To support encrypted HTTP (HTTPS) downloads, Wget must be compiled with an external SSL library, currently OpenSSL. If Wget is compiled without SSL support, none of these options are available. 

---

I'm sure I'm not the first person to land here without a paddle ;)

**Comment by joejoseph00** [comment]
"Maybe on Monday I can add --no-check-certificate to my local temp copy of build-wetkit.make. Hold on. How? "

adding --no-check-certificate  is a good idea

Try to download a version of Wget that's already compiled with the external SSL library.

OR, you could try the Vagrant Chef version of WETBOEW.  I haven't tried this yet because we use LAMP.

https://github.com/wet-boew/ariadne-wet-boew-drupal

**Comment by WayneWhitten** [comment]
I wish I know how to respond directly under joejoseph00's earlier response.  Maybe someone can help me with that too.

WAMP 2.2 on Windows 2008 R2 Standard using VMware
- PHP 5.3.13
- MySQL 5.5.24
- Apache 2.2.22
- Drush 5.8

I've since used a laptop that already had a successfully installed version of Acquia Desktop.  Everything installed fine.  I believe the difference is the virtual machine/server, and perhaps some of my profile or environment settings.
- K drive is used for my .drush directory instead of (what I believe should be my) local drive.  K is already mapped in my environment as my HOMEDRIVE.
- I've tried Acquia's Desktop installation a few years ago on a virtual server with no success.  Haven't tried it since then until now.

When attempting the Drush process on the virtual server it would stall out after the copy process, so I never got all the files.  I certainly couldn't progress with the subsequent steps including the Make process.

Installing on a physical machine alleviated both issues above.  I also had to open up the permissions on the destination directory.

I'd like to find out why the virtual server was such a problem.  I remember trying to reset the HOMEDRIVE to something local to the server like C:\tmp but can't remember the results.  Obviously if it worked back then I would have kept going, but that wasn't the case.

Resulting issue:  Now that the Canada WET site is installed (albeit not on the preferred server) I need to get the Acquia Desktop to recognize it and make it available.  Do I "Import" it, or use it where it is?  What's the procedure?  I realize this is probably stretching the scope of this forum, but I feel like the instructions are missing a few remaining steps.  Let me know if I need to open a different issue for this.

**Comment by alar2** [comment]
Hi Wayne, Sorry for hi-jacking your topic! Your initial question is exactly what I want to solve!
I am trying to deploy to a DEV Server -- Windows 2008 R2 and I believe it is a Virtual Machine.
My Proof of Concept "Windows" was on Virtual Box Windows 7 using Acquia as a WAMP install and all is well!!
(I own the machine and it is CentOS running Windows 7 Virtual Box)
I also had success on my local work machine (XP) using XAMPP not Acquia setup.
I thought I was good to go!
While the client is chomping at the bit I am ready to bring my personal Windows 7 - Oracle VM Virtual Box for demo. Better yet I should suggest a Linux base install Virtual Box... 
Not a solution... ;P
I think you are ahead of me! Don't you only have to set up Virtual Host to point to the webserver? It's in the file that says don't edit me!
My successful Windows 7 install is using Aquia environment with Git bash, and I am working in /c/users/myname/Sites/drupal_wet. 

```
PHP 5.3.6 (cli)
MySQL 5.1.66, for win32 (ia32)
Apache 2.2.22
Drush 5.8
Git version 1.8.1.
```

If I have time, which I don't. I wish I had used these versions on my last attempt to deploy to Windows 2008. The other funny bit is trying to deploy to e:\htodocs\sites\drupal_wet in lieu of home directory. 

You're not alone Wayne!! :) Agggh!
Cheers,
Allison

**Comment by joejoseph00** [comment]
@WayneWhitten ,  a quick overview of how this installation works.  Although I've never installed this on Windows, I can give you a quick rundown.

WETBOEW-drupal project stores the Drupal core, contrib modules, WETBOEW-drupal custom modules and configuration on Github , you need to have a machine to install onto that has the prerequisites (Git 1.7 or Git 1.8 , drush, mysql, a web server (nginx, iis or apache) wget, php 5.3 , if you're missing something the error message should tell you during the build script run ) the build script will install into the directory name defined in the build parameters (a folder say "wetboew" in the current directory.   your web server has to have that in it's virtual directory configuration, see Drupal.org on configuring a virtual directory for your web server that serves up Drupal.

when you run the build you pass the parameters for your mysql connection (user , password, hostname) the build script runs, grabs all files from github wetboew-drupal which includes a custom drupal installation script that creates the tables and populates them, you might get some warning messages during this build, no problem, if there's an error put it up here for people to look at and maybe we can figure it out.  

The fact that you're getting a wget error , lets focus on that, you'll need to get past that first.

The other option, if you want, you can probably just do a git clone of the whole wetboew-drupal folder and then instead of running the installation build script do a MANUAL drupal installation, (if the web gui drupal installation failes you could try manually copying sites/default/default-settings.php to sites/default/settings.php and update settings.php accordingly) very easy, just do a git clone of this WETBOEW-drupal repo, then go to your web browser and the standard drupal install script should run automatically, if it doesn't double check the .htaccess file, or double check your virtual folder configuration .

Otherwise, try to find someone on here that's done this on WAMP.  I haven't.  

I know it works, someone (I think from RCMP) even installed WETBOEW onto MSSQL using a WAMP stack.  Although he had to upstream some fixes (done).  I would recommend MySQL though, it's very good.

**Comment by alar2** [comment]
Hi Wayne,
Any luck?  I re-read your original error and it may be your Drush install.
"In case you still don't know how important it is to register environment variables See: Install Drush to work with Git Bash Window:
https://drupal.org/node/1843176
You should be able to run Drush from within the Git Bash Window! "
HTH

**Comment by sylus** [comment]
Closing this as no new feedback.
