### ISSUE TITLE
Data.gc.ca Launch

### ISSUE THREAD

**Issue by sylus** [wet-boew/wet-boew-drupal#932]
Hey wanted to state that data.gc.ca has finally launched.

As such me and my team can finally devote time back to this repo. Apologies for being away. There is going to be a lot of code pushed during the next few days so be prepared!

Anyways please everyone take a look at data.gc.ca and get ready for some awesome contributions to be made available. I am very excited to bring this code forward. There will also be an article written soon about apachesolr_views + apachesolr multilingual which might be of some interest to certain departments.

Impressive pages on data.gc.ca are:

http://data.gc.ca/apps
http://data.gc.ca/search/ati

In terms of code improvements there is actually a lot of work that will make its way in, particularly in terms of accessibility as we have run rather in depth scans with CSEValidator, W3C, Contrast Ratio, and Squiz Labs. We have also had impaired users navigate the site in order to improve other areas of the site that can't be scanned automatically and require actual testing.

Stay tuned!

**Comment by nschonni** [comment]
Congrats!
Few notes that you should feel free to ignore because I don't know Drupal:
- Any reason you're using jQuery 1.7.1? 3.1 split the support between 1.9 (and 1.10 in master) for IE and 2.0 for modern.
- A bunch of the JS isn't minified
- Saw one or two workarounds for "old" jQuery 1.6 issues
- jQuery UI Tabs 1.8.11 is being loaded as part of a jQuery UI bundle

**Comment by sylus** [comment]
Thanks @nschonni please fell free to file more issues as we want this to be the go to Drupal site.

1) For jQuery 1.7 we had to use that as was the most tested with Drupal but in phase 2 will be separating out the front end jquery vs back end jquery so can use a later version
2) Some of the JS that isn't minified is likely an oversight on our part I'll look into this but might be solved when we use drupal.org/project/advagg which also lets us compress according to media query
3) I'd appreciate more info on this one.
4) Need more info on this one as well.

Please let us know about more issues as well!

**Comment by nschonni** [comment]
Sorry, because of the asset management pipeline, I don't know if any of the URLs are traceable. All this info was just gotten from using the Chrome F12 tools to look at the Network\Scripts tab (Firebug does the same).

2) Actually, when I say some, it's actually none except the core WET files and the jQuery UI stuff.

3) Here is the chunk from http://data.gc.ca/sites/data.gc.ca/files/js/js_daB6IKr3aS1nQzl7NoGDQfrzt5yVWd0b-nj_aPvwrRE.js

``` js
/*
 * Check whether the hostname is part of the cross domains or not.
 *
 * @param string hostname
 *   The hostname of the clicked URL.
 * @param array crossDomains
 *   All cross domain hostnames as JS array.
 *
 * @return boolean
 */
function isCrossDomain(hostname, crossDomains) {
  /**
   * jQuery < 1.6.3 bug: $.inArray crushes IE6 and Chrome if second argument is
   * `null` or `undefined`, http://bugs.jquery.com/ticket/10076,
   * https://github.com/jquery/jquery/commit/a839af034db2bd934e4d4fa6758a3fed8de74174
   *
   * @todo: Remove/Refactor in D8
   */
  if (!crossDomains) {
    return false;
  }
  else {
    return $.inArray(hostname, crossDomains) > -1 ? true : false;
  }
}
```

4) http://data.gc.ca/sites/data.gc.ca/files/js/js_ZpJJbWcnnM1coYfZHlZbonoPG7yc97Gp-EA83pwd1VI.js was the link I was looking at, but it is a single js file with jQuery UI, Widget, Tabs, and According. There may be a hard dependency between Accordion and Tabs in that version of UI.

**Comment by sylus** [comment]
Thanks for the taking the time @nschonni I am going to be taking a look at this tomorrow :)

**Comment by mgifford** [comment]
Great work! One thing that occurred to me when looking at the site is that it would be useful to have a WET specific launch checklist.

Did you use one with data.gc.ca?  Might be useful to just have a wiki page with that in it.  Maybe even something built on top of https://drupal.org/project/qa_checklist

**Comment by nschonni** [comment]
GZIP would reduce page size by 70% according to PageSpeed https://developers.google.com/speed/pagespeed/insights#url=http_3A_2F_2Fdata.gc.ca_2Feng&mobile=false
Which is also a good preflighting (using the plugin)/postflight using the site (which is a little more powerful)

**Comment by joejoseph00** [comment]
Great job Sylus on the data.gc.ca site!    Looking forward to seeing RC 2 of wetboew-drupal.

**Comment by sylus** [comment]
Closing this issue but will file new ones shortly based on nshonni's feedback.
