### ISSUE TITLE
Need better install instructions for MSSQL

### ISSUE THREAD

**Issue by mgifford** [wet-boew/wet-boew-drupal#946]
I'm attempting to document a IIS / MSSQL Server implementation of WET.

From the windows MySQL explanation I think it should be

C:\inetpub\wwwroot>drush si wetkit wetkit_wetboew_selection_form.theme=wetkit_adaptivetheme --sites-subdir=drupal_wet --db-url=mysql://drupalusr:drupalusr_pass@localhost:3306/wetkit_db --account-name=admin --account-pass=WetKit@2012 --account-mail=admin@example.com --site-mail=admin@example.com --site-name="Web Experience Toolkit"

 install I think I should be able to do:
C:\inetpub\wwwroot>drush si wetkit wetkit_wetboew_selection_form.theme=wetkit_adaptivetheme --sites-subdir=drupal_wet --db-url=mssql://drupalusr:drupalusr_pass@localhost:1433/wetkit_db --account-name=admin --account-mail=admin@example.com --site-mail=admin@example.com --site-name="Web Experience Toolkit"

I couldn't copy that from the Drush shell, so who knows if that's exactly letter for letter what I typed in.

In anycase, what I get is "No query provided" immediately after confirming "You are about to CREATE the 'wetkit_db' database. Do you want to continue?"

Since it seems like we can now build WET on Drush 5.8 for windows, would be good if we have the proper syntax.

**Comment by RobJohnston** [comment]
I assumed early on that the --db-url parameter wasn't capable of mssql and have been installing via the GUI.  I'd be interested to know if it actually works.

P.S. You can copy-and-past from the command line in Windows by right-clicking, selecting "Mark", and then left-click-and-drag to cover what you want to copy.  Then right-click again when all is selected to copy that selected text.  Simple, eh?

**Comment by mgifford** [comment]
I was getting confused by all the terminals that i needed.  There's the Git one, Drush one & then the good old fashioned one.  I thought I could cut/paste from one of them, but...

I should also just try the tarball from drupal.org too and see how that works.

**Comment by RobJohnston** [comment]
There is one patch that is still required (as of today) for MSSQL, or else beans cannot be created.  Follow the threads at https://github.com/wet-boew/wet-boew-drupal/issues/745#issuecomment-16386564.

**Comment by RobJohnston** [comment]
Just recalled another oddity with MS SQL Server... clicking the "Francais" button won't work correctly unless you first go to "/admin/config/regional/language" and click "Save Configuration"... you don't have to actually change anything, but it needs to be re-saved.  Tested that 5 minutes ago and it's still an issue, but not for MySQL or PostGres.
Edit:  See issue #631.

**Comment by mgifford** [comment]
That is just weird..  But a great tip, thanks!

**Comment by RobJohnston** [comment]
Hi @mgifford,

I re-visited the command line install after browsing the drush source code because I noticed that MS SQL Server was identified as sqlsrv instead of mssql.  I think there might be a chance of doing a command-line install with a line like the following:

``` drush
drush si wetkit wetkit_theme_selection_form.theme=wetkit_omega install_configure_form.demo_content=TRUE --sites-subdir=default --db-url=sqlsrv://drupalusr:drupalpass@127.0.0.1:1433/wetkit_db --account-name=admin --account-pass=WetKit@2013 --site-mail=admin@example.com --site-name='Web Experience Toolkit' --yes
```

I just tried it on our maintenance server but it won't get too far because there are calls to the sqlcmd utility (that isn't installed on that machine).  Looks promising, though.

I believe that the use of sqlcmd instead of osql or isql requires SQLServer 2005 or higher.  What installs it would likely be SQL Server client tools or maybe even Visual Studio

**Comment by RobJohnston** [comment]
Correction to last... that sucker just ran!  

The one error was due to trying to create an index on a varchar(max) field and I think a key in MS SQL Server can't be over 450 characters.  Haven't found an issue in Drupal for this yet.

Here's the final output:

You are about to CREATE  the 'wetkit_db' database. Do you want to continue? (y/n): y
'sqlcmd' is not recognized as an internal or external command, operable program or batch file.
Starting Drupal installation. This takes a few seconds ...                                                               [ok]

WD database: PDOException: SQLSTATE[42000]: [Microsoft][SQL Server Native Client 11.0][SQL Server]Column 'source'     [error]

in table 'locales_source' is of a type that is invalid for use as a key column in an index.: CREATE INDEX
source_context_idx ON [{locales_source}](source, context); Array
(
)
 in db_create_table() (line 2717 of D:\internet\drupal_WxT\includes\database\database.inc).
Processed 3 (1 created, 2 updated, 0 failed, 0 ignored) in 0.3 sec (549/min) - done with 'WetKitMigrateMegaMenu'  [completed]

Processed 4 (0 created, 4 updated, 0 failed, 0 ignored) in 0.2 sec (1099/min) - done with 'WetKitMigrateSiteMenu' [completed]

Processed 50 (50 created, 0 updated, 0 failed, 0 ignored) in 2.3 sec (1282/min) - done with                       [completed]

'WetKitMigrateSiteMenuLinks'
Processed 6 (3 created, 3 updated, 0 failed, 0 ignored) in 131.7 sec (3/min) - done with                          [completed]

'WetKitMigrateDefaultContent'
Processed 136 (136 created, 0 updated, 0 failed, 0 ignored) in 7 sec (1168/min) - done with                       [completed]

'WetKitMigrateMegaMenuLinks'
Installation complete.  User name: admin  User password: WetKit@2013                                                    [ok]

**Comment by RobJohnston** [comment]
Hi again @mgifford, there's one more (new) patch required for sqlsrv (and possibly some versions of postgres).  Otherwise, the /admin/content/file/thumbnails page is broken. See comment # 5 of https://drupal.org/node/2078393.

Amazingly, there are only 2 sqlsrv specific patches so far!

**Comment by mgifford** [comment]
That's great to hear. Btw, you don't have any easy ways to migrate from MySQL to MSSQL do you? There are lots of ways to do it from what I've read, but none of them seem to be all that straight forward.

**Comment by RobJohnston** [comment]
Nope, I've only ever migrated from MS SQL or from the file system, every time using the migrate module.

**Comment by joejoseph00** [comment]
I think we can close this as I don't know of any organisation still using MS SQL with the wetkit distro.  We don't recommend running the wetkit distro with MS SQL at this time however please feel free to do so at your own expense.

**Comment by RobJohnston** [comment]
Hey @jamessauve, isn't PCO still using MS SQL Server?

**Comment by jamessauve** [comment]
Yeah, we're not among the cool kids who get to play with LAMP.  But were used to figuring things out for ourselves. Besides all this shit is going over to Adobe isn't it?

**Comment by joejoseph00** [comment]
PCO isn't using wetkit

**Comment by jamessauve** [comment]
We aren't?  Hmmm... that's news to me.

**Comment by joejoseph00** [comment]
News to me.  I was told by several people that the 24 seven website was NOT wetkit

**Comment by jamessauve** [comment]
24 Seven Daily is far from our only website (but it is our only one not using wetkit).

**Comment by joejoseph00** [comment]
I might be joining your team, good to know that I'll be using wetkit.

**Comment by jamessauve** [comment]
You want to willing work at a Microsoft shop?  I hope you handle frustration well.

**Comment by joejoseph00** [comment]
Frustration fills bank accounts with many extra zeros.

**Comment by jamessauve** [comment]
Good, you'll need it. ;)

**Comment by jamessauve** [comment]
On plus side, I take it we can keep this open as now you know of one pretty significant department using mssql?

**Comment by joejoseph00** [comment]
If I join your team I'll work on this issue for sure.

**Comment by xmacinfo** [comment]
In addition to the two patches mentionned earlier to have Drupal use SQL Server, is there a list of modules that works with SQL Server? Does a lot of modules require their own patch?

**Comment by RobJohnston** [comment]
Some modules did require patches to work with SQL Server and some didn't... it's a hit-and-miss kind of game.  

I had submitted patches for the modules we used that needed them.  Some module maintainers quickly merged the patch, others took their sweet time, and I even remember that there was one module (forget the name) that would close all issues because it wasn't related to MySQL.

**Comment by mgifford** [comment]
Always good to tag them so that it is easier to find/prioritize them in the future https://www.drupal.org/project/issues/search?issue_tags=mssql

Just because a maintainer closes an issue, doesn't mean it can't be re-opened in most open source projects.

**Comment by jamessauve** [comment]
We're definitely second class citizens, even some update to modules that work beautifully with mssql bomb on the update because the expectation and testing is only mysql.  Ottawa U's secure syndication doesn't work at all on mssql, end of story, it just doesn't.  Other modules are like that too.  Can be frustrating if it's something that would really make you life easier.

**Comment by joejoseph00** [comment]
Is this on the Radar?  http://www.mysql.com/why-mysql/white-papers/guide-to-migrating-from-sql-server-to-mysql/ Time for sales pitch. (its free! and it's better!)  If you need a stack change, I'd love to be a part of it.

**Comment by jamessauve** [comment]
Although I would love to see this happen, it's not likely our management would allow it.

**Comment by mgifford** [comment]
I was told by a Windows sales guy at DrupalCon a while back to use Windows Server 2012 & MySQL.  He said that the PHP drivers for MSSQL just hadn't been kept up and that.  He told me that was the best practice for a Windows Server.  

That might have changed, but ya, I really can't see any advantage to sticking with MSSQL other than that's what the corporate policy is.

**Comment by joejoseph00** [comment]
Mike Gifford, your documentation was a real asset to figure out how to get the distro working with mssql and iis.  In case anyone stumbles here, the next release of the distro will include Drupal core 7.41 which includes improved compatibility with the sqlsrv project (http://www.drupal.org/project/sqlsrv ) getting mssql to work with the distro wasn't that hard, I had a bit of trouble with D7 core 7.39 but found a patch, D7 core 7.41 does not need the patch as it's already included so this won't be an issue going forward.  To get sqlsrv working (mssql) with Drupal follow the instructions on the sqlsrv project http://www.drupal.org/project/sqlsrv and also a great help was the docs made by Mike Gifford here available on github.  Thanks Mike

**Comment by mgifford** [comment]
Thanks Joseph. Our guide is available as a PDF here http://openconcept.ca/sites/openconcept/files/u40/drupalwetwindowsbuilddocument.pdf

Glad it's gotten easier with 7.41.
