### ISSUE TITLE
Need documentation for the three default Mega Menus

### ISSUE THREAD

**Issue by MikeDucharme** [wet-boew/wet-boew-drupal#969]
After installing Wetkit, there are three mega menus that are automatically generated. It is unclear what the purpose of the "Mega Menu (focus)" and "Mega Menu (insert)" are. Can anyone provide or point me to some documentation on this? Do they integrate with any Wetkit libraries?

**Comment by mgifford** [comment]
@sinkinsona Even a brief description of the two would be useful.  Can you assign this to someone?

**Comment by sinkinsona** [comment]
@mgifford We will be creating some documentation and posting it online to better explain the menus that are automatically generated.  Also we will explain how to configure the mega menu as this has changed and uses mini panels.

**Comment by joejoseph00** [comment]
working on it

**Comment by mgifford** [comment]
Just to be very clear.  This doesn't need to be polished documentation that is spell checked, translated & includes screen shots.  

Even something along the lines of:
- Use X for these items
- Use Y for these items
- Use Z for anything else

Ideally this would be documented clearly in the interface so that nobody would even think of asking this question because it's so obvious.  

However, ultimately having some text guide even attached to this issue would be sufficient while the code is still in flux.

**Comment by joejoseph00** [comment]
Just installed RC10, but would like to test the megamenu in both languages and noticed that the distro no longer includes french translations for Drupal core.  And during installation if you select "French" it does the same thing as if you select "English".  I've successfully imported drupal-7.23.fr.po manually.  Had a bit of trouble finding the "import" button because it's located at the top left of the div instead of the top right of the div like in a standard drupal install (my book had a screenshot of a base Drupal admin interface and it looks nothing like the RC10 admin interface)

**Comment by mgifford** [comment]
I couldn't test this in SimplyTest.me as there was a problem with their infrastructure (I think).

@sylus Should we be posting the French issue that @joejoseph00 mentioned in https://drupal.org/project/issues/wetkit?categories=All

**Comment by sylus** [comment]
Yeah sure go ahead.

**Comment by joejoseph00** [comment]
testing the megamenu functionality on RC11 , I noticed one anomaly that I'll be re-testing tomorrow.  Not sure if it was data-entry problem or otherwise.  I'll test more tomorrow.  Docs to follow.

**Comment by MikeDucharme** [comment]
Any progress on the documentation for this?

**Comment by fgjohnson** [comment]
See #1483 
Anyone ?

**Comment by sylus** [comment]
The menu system in the 4.x branch doesn't do anything fancy like mini panels and lets the Bootstrap base theme handle the menu system in Drupal. So no mini panels just menu links at this point. Keeping it simple ^_^

**Comment by joejoseph00** [comment]
It would be nice to have 4 level deep menus .

There's a patch here for the sidebar: https://www.drupal.org/node/2485817

would be cool to have something similar to the sidebar patch that works for the main menu out of the box.

**Comment by joejoseph00** [comment]
but ya, I was pleased with the sidebar 4 levels deep .  we got that working , the client is happy.
https://www.drupal.org/node/2485817

**Comment by rdrew** [comment]
I can still find absolutely no info on the menu system in v4.x. Has there been any progress?

**Comment by sylus** [comment]
The menu system in 4.x is using the native drupal menu system. If you install the distro with the default demo content you can see how the menu works but in essence just involves going to:

1) admin/structure/menu
2) select the menu you want to configure / add menu links to (for instance megamenu)
3) then add the appropriate links

The default menu system documentation Drupal provides can be found here:

https://www.drupal.org/documentation/modules/menu

**Comment by rdrew** [comment]
Thanks for the response. So, what is the distinction between Megamenu, Megamenu (insert) and Megamenu (focus)?

**Comment by sylus** [comment]
In 4.x you should only be concerned about Megamenu, the other 2 are legacy menus that were kept in order to facilitate an upgrade path from 1.x where those menus were needed with mini panels. That approach is deprecated in 4.x in favor of just using the native way.
