### ISSUE TITLE
Second level Mega menu items are not getting linked.

### ISSUE THREAD

**Issue by irummaqsood** [wet-boew/wet-boew-drupal#984]
I have a mega menu that has 2 level links. The second level menu items (Buying and Selling, Payments and Pensions etc)  have links associated to them, but the links are not showing up in code.

![megamenu](https://f.cloud.github.com/assets/3999431/1160373/d160b852-1fd7-11e3-9fc3-482830415e36.JPG)

**Comment by sinkinsona** [comment]
Hi @irummaqsood - what version of the distro are you running?  We have made changes to the mega menu to use mini panels so that it can handle many use cases / options that our business clients want.  The down side is that it is more complex then a traditional Drupal menu but it can be configured to do a lot of cool things like supporting views, images etc..  In this issue https://github.com/wet-boew/wet-boew-drupal/issues/969 we will provide a link to documentation that we fully explain how the mega menu is configured.  If you create a new instance of the distro and import the sample content it will create some menu links supporting the use case above.

![screen shot 2013-09-17 at 8 16 32 pm](https://f.cloud.github.com/assets/1258144/1161881/5ac67186-1ffb-11e3-85ac-d85497c64372.png)

**Comment by irummaqsood** [comment]
I am using v1.0-RC7. I installed the new distribution 2 days ago. The link WET-BOEW is working for me but when I add my own links the second level links are not working. I looked at the code and it looks like a class no-link is being added to my <h4>....

**Comment by sylus** [comment]
Alot of work has been done to the menu system. Can you take a look at this again. Also should file future issues on Drupal.org.
